### ISSUE TITLE
0.18 seems to break my application?

### ISSUE THREAD

**Issue by dstlny** [tortoise/tortoise-orm#1014]
**Describe the bug**
Versions below 0.18, work fine... but 0.18 will randomly throw exceptions like the following:

C:\Users\dstlny\projects\ProductionProject>"C:/Program Files/Python38/python.exe" c:/Users/dstlny/projects/ProductionProject/backend/app.py
INFO:     2021-12-22 17:13:39 - uvicorn.error:serve:64 - Started server process [7724]
INFO:     2021-12-22 17:13:39 - uvicorn.error:startup:26 - Waiting for application startup.
INFO:     2021-12-22 17:13:39 - tortoise:init_orm:94 - Tortoise-ORM started, {'default': <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x000001CE07F81A30>}, {'models': {'Site': <class 'api_v1.admin.models.Site'>, 'SystemNotifications': <class 'api_v1.admin.models.SystemNotifications'>, 'Chat': <class 'api_v1.auth.models.Chat'>, 'Message': <class 'api_v1.auth.models.Message'>, 'Permission': <class 'api_v1.auth.models.Permission'>, 'Post': <class 'api_v1.posts.models.Post'>, 'PostCategory': <class 'api_v1.posts.models.PostCategory'>, 'Token': <class 'api_v1.auth.models.Token'>, 'User': <class 'api_v1.auth.models.User'>, 'UserRequests': <class 'api_v1.auth.models.UserRequests'>, 'Asset': <class 'api_v1.common.models.Asset'>, 'Reactions': <class 'api_v1.common.models.Reactions'>, 'Tasks': <class 'api_v1.common.models.Tasks'>, 'Comment': <class 'api_v1.comments.models.Comment'>, 'Aerich': <class 'aerich.models.Aerich'>}}
INFO:     2021-12-22 17:13:39 - tortoise:init_orm:96 - Tortoise-ORM generating schema
INFO:     2021-12-22 17:13:39 - uvicorn.error:startup:38 - Application startup complete.
INFO:     2021-12-22 17:13:39 - uvicorn.error:_log_started_message:199 - Uvicorn running on http://192.168.0.33:8000 (Press CTRL+C to quit)
INFO:     2021-12-22 17:13:39 - root:create_builtin_tasks:130 - Took 0.00s | 0 ROWS AFFECTED
ERROR:    2021-12-22 17:13:39 - asyncio:default_exception_handler:1707 - Job processing failed
job: <Job coro=<<coroutine object func_logger at 0x000001CE06FBD040>>>
Traceback (most recent call last):
  File "asyncpg\protocol\prepared_stmt.pyx", line 155, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg\protocol\codecs/base.pyx", line 193, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg\protocol\codecs/base.pyx", line 104, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg\pgproto\./codecs/json.pyx", line 13, in asyncpg.pgproto.pgproto.jsonb_encode
  File "asyncpg\pgproto\./codecs/text.pyx", line 12, in asyncpg.pgproto.pgproto.as_pg_string_and_size
TypeError: expected str, got bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\backends\asyncpg\client.py", line 36, in translate_exceptions_
    return await func(self, *args)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\backends\asyncpg\client.py", line 178, in execute_query       
    res = await connection.execute(*params)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 299, in execute
    _, status, _ = await self._execute(
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 1625, in _execute
    result, _ = await self.__execute(
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 1650, in __execute
    return await self._do_execute(
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 1697, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg\protocol\protocol.pyx", line 181, in bind_execute
  File "asyncpg\protocol\prepared_stmt.pyx", line 171, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $3: b'{}' (expected str, got bytes)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\dstlny\projects\ProductionProject\backend\api_v1\initialiser.py", line 138, in func_logger
    await task.save()
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\models.py", line 951, in save
    await executor.execute_update(self, update_fields)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\backends\base\executor.py", line 315, in execute_update
    await self.db.execute_query(
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\backends\asyncpg\client.py", line 38, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: invalid input for query argument $3: b'{}' (expected str, got bytes)

**To Reproduce**
Be using 0.18, and use posrgres with asyncpg.

Seems to be happening whenever anything is attemptedly saved to the database, though it's really sporadic.

Getting this with Aerich, too, whenever i try init-db, for example:

C:\Users\dstlny\projects\ProductionProject\backend>aerich init-db
Traceback (most recent call last):
  File "asyncpg\protocol\prepared_stmt.pyx", line 155, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg\protocol\codecs/base.pyx", line 193, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg\protocol\codecs/base.pyx", line 104, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg\pgproto\./codecs/json.pyx", line 13, in asyncpg.pgproto.pgproto.jsonb_encode
  File "asyncpg\pgproto\./codecs/text.pyx", line 12, in asyncpg.pgproto.pgproto.as_pg_string_and_size
TypeError: expected str, got bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\backends\asyncpg\client.py", line 36, in translate_exceptions_
    return await func(self, *args)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\backends\asyncpg\client.py", line 150, in execute_insert
    return await connection.fetchrow(query, *values)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 641, in fetchrow
    data = await self._execute(
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 1625, in _execute
    result, _ = await self.__execute(
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 1650, in __execute
    return await self._do_execute(
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 1697, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg\protocol\protocol.pyx", line 181, in bind_execute
  File "asyncpg\protocol\prepared_stmt.pyx", line 171, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $3: b'{"models.Site":{"name":"models.Site","... (expected str, got bytes)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\program files\python38\scripts\aerich.exe\__main__.py", line 7, in <module>
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\aerich\cli.py", line 257, in main
    cli()
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\aerich\cli.py", line 32, in wrapper
    loop.run_until_complete(f(*args, **kwargs))
  File "c:\program files\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\aerich\cli.py", line 232, in init_db
    await command.init_db(safe)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\aerich\__init__.py", line 130, in init_db
    await Aerich.create(
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\models.py", line 1117, in create
    await instance.save(using_db=db, force_create=True)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\models.py", line 938, in save
    await executor.execute_insert(self)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\backends\base\executor.py", line 225, in execute_insert
    insert_result = await self.db.execute_insert(self.insert_query, values)
  File "C:\Users\dstlny\AppData\Roaming\Python\Python38\site-packages\tortoise\backends\asyncpg\client.py", line 38, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: invalid input for query argument $3: b'{"models.Site":{"name":"models.Site","... (expected str, got bytes)

**Expected behavior**
These errors should not be thrown...

**Additional context**
Anything below tortoise-orm==0.18 seems to work

Python: 3.8.5

Any if you ask :)

**Comment by long2ice** [comment]
Try last source code

**Comment by dstlny** [comment]
> Try last source code

Yup - can confirm, that seems to have resolved it :)
