### ISSUE TITLE
 Abnormal operation of version 0.19.1

### ISSUE THREAD

**Issue by tqq1994516** [tortoise/tortoise-orm#1150]
**Describe the bug**
tortoise-orm             0.19.1

**To Reproduce**
Make mistakes when I use the following grammar：
await Permissions.exists(Q(models=pk.id) & Q(name=p))

**Expected behavior**
Version 0.19.0 can be used normally

**Additional context**

Traceback (most recent call last):
Errors are reported as follows：
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/server/runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/app.py", line 1581, in _server_event
    await self.dispatch(
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/signals.py", line 163, in _dispatch
    retval = await maybe_coroutine
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/app.py", line 1144, in _listener
    await maybe_coro
  File "/root/test_platform/signals.py", line 75, in load_permission
    if not await Permissions.exists(Q(models=pk.id) & Q(name=p)):
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/tortoise/queryset.py", line 1216, in _execute
    result, _ = await self._db.execute_query(str(self.query))
AttributeError: 'Q' object has no attribute 'execute_query'
Traceback (most recent call last):
  File "/root/test_platform/main.py", line 14, in <module>
    app.run(host=HOST, port=PORT, dev=DEV, access_log=ACCESS_LOG, fast=FAST)
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/mixins/runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/server/runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/app.py", line 1581, in _server_event
    await self.dispatch(
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/signals.py", line 163, in _dispatch
    retval = await maybe_coroutine
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/sanic/app.py", line 1144, in _listener
    await maybe_coro
  File "/root/test_platform/signals.py", line 75, in load_permission
    if not await Permissions.exists(Q(models=pk.id) & Q(name=p)):
  File "/root/miniconda3/envs/test_platform/lib/python3.9/site-packages/tortoise/queryset.py", line 1216, in _execute
    result, _ = await self._db.execute_query(str(self.query))
AttributeError: 'Q' object has no attribute 'execute_query'
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited

**Comment by tqq1994516** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
