### ISSUE TITLE
Pylint crashes due to Tortoise ORM's plugin

### ISSUE THREAD

**Issue by mbayabo** [tortoise/tortoise-orm#1159]
Issue title:

Crash ``Building error when trying to create ast representation of module 'api.units.models'``
Content:
When parsing the following file:

```python
from uuid import uuid4

from tortoise import fields, models


class Unit(models.Model):
    id = fields.UUIDField(pk=True, default=uuid4)
    material = fields.ForeignKeyField(
        model_name="api.Material",
        on_delete=fields.RESTRICT,
        related_name="units",
    )
    serial_number = fields.CharField(max_length=100)

    created_at = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "units"

```

pylint crashed with a ``AstroidBuildingError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 888, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/builder.py", line 134, in file_build
    return self._post_build(module, builder, encoding)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/builder.py", line 160, in _post_build
    module = self._manager.visit_transforms(module)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/manager.py", line 79, in visit_transforms
    return self._transform.visit(node)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/transforms.py", line 88, in visit
    return self._visit(module)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/transforms.py", line 53, in _visit
    visited = self._visit_generic(value)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/transforms.py", line 60, in _visit_generic
    return [self._visit_generic(child) for child in node]
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/transforms.py", line 60, in <listcomp>
    return [self._visit_generic(child) for child in node]
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/transforms.py", line 66, in _visit_generic
    return self._visit(node)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/transforms.py", line 56, in _visit
    return self._transform(node)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/astroid/transforms.py", line 38, in _transform
    ret = transform_func(node)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/tortoise/contrib/pylint/__init__.py", line 58, in transform_model
    tomodel = attr.value.args[0].value
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 684, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 716, in _check_file
    ast_node = get_ast(file.filepath, file.name)
  File "/home/mikko/.cache/pypoetry/virtualenvs/data-api-vbfNBv9P-py3.9/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 907, in get_ast
    raise astroid.AstroidBuildingError(
astroid.exceptions.AstroidBuildingError: Building error when trying to create ast representation of module 'api.units.models'
```

I've also isolated the issue:
The keyword argument `model_name` for `fields.ForeignKeyField`, if explicitly written, will cause this crash.

This works:
```python
class Unit(models.Model):
    id = fields.UUIDField(pk=True, default=uuid4)
    material = fields.ForeignKeyField(
        "api.Material",
        on_delete=fields.RESTRICT,
        related_name="units",
    )
    serial_number = fields.CharField(max_length=100)

    created_at = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "units"
```

Upon further inspection. I think I can fix this issue if you'd let me try.

**Comment by long2ice** [comment]
Looks like problem of pylint?

**Comment by mbayabo** [comment]
This is the exact line that assumes that a positional argument is given.

```python
tomodel = attr.value.args[0].value
```
At line 58 of `tortoise.contrib.pylint`

https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/contrib/pylint/__init__.py

I can attempt to fix this myself, if you'd like and ask for a PR

**Comment by long2ice** [comment]
Yes, feel free to make a PR

**Comment by mbayabo** [comment]
This bug is now fixed
