### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'acquire'

### ISSUE THREAD

**Issue by ivictor777** [tortoise/tortoise-orm#1177]
**Describe the bug**
I am fetching from a table in multiple tasks via asyncio (I additionally use arq as a queue manager) and sometimes I get this error on this line:
project = await CloudProject.filter(name=project_name).first()

failed, AttributeError: 'NoneType' object has no attribute 'acquire'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 525, in run_job
    result = await task
  File "/Users/victor/Developer/yt/enqueue_jobs2.py", line 40, in process_business_account
    await instance_for_chrome.create()
  File "/Users/victor/Developer/yt/deployment.py", line 41, in create
    project = await self._get_project_fake()
  File "/Users/victor/Developer/yt/deployment.py", line 100, in _get_project_fake
    project = await CloudProject.filter(name=project_name).first()
  File "/usr/local/lib/python3.9/site-packages/tortoise/queryset.py", line 1006, in _execute
    instance_list = await self._db.executor_class(
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/base/executor.py", line 130, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/mysql/client.py", line 44, in translate_exceptions_
    return await func(self, *args)
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/mysql/client.py", line 196, in execute_query
    async with self.acquire_connection() as connection:
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/base/client.py", line 328, in __aenter__
    self.connection = await self.pool.acquire()
AttributeError: 'NoneType' object has no attribute 'acquire'

**Comment by ivictor777** [comment]
I'm sorry, I didn't use the initialization correctly, the code below works great.:

```
from models import CloudProject
import asyncio
import configs.db
from tortoise import Tortoise

from arq import create_pool
from arq.connections import RedisSettings

async def get_project(ctx):
        
        project_name = 'project1'
        project = await CloudProject.filter(name=project_name).first()
        print(project.id)


async def run():
    redis = await create_pool(RedisSettings())
    for i in range(50):
        await redis.enqueue_job('get_project')
    
async def startup(ctx):
    await Tortoise.init(config=configs.db.TORTOISE_ORM)

class WorkerSettings:
    functions = [get_project]
    health_check_interval = 1
    max_jobs = 5
    max_tries = 1
    on_startup = startup

if __name__ == "__main__":
    asyncio.run(run())
```
