### ISSUE TITLE
default value on PK field does not work

### ISSUE THREAD

**Issue by iyuhang** [tortoise/tortoise-orm#1268]
**Describe the bug**
default value on PK field does not work

**To Reproduce**

MODEL:
```
class User(Model):
	id = fields.BigIntField(pk=True, default=6)
```

Action:

```
user = User()
user.save()
```

Report:

```
Traceback (most recent call last):
  File "handle_request", line 96, in handle_request
    if TYPE_CHECKING:
  File "/Users/apple/SynologyDrive/code/rena_sanic/account/views.py", line 18, in get
    await user.save()
  File "/Users/apple/opt/anaconda3/envs/sanic/lib/python3.9/site-packages/tortoise/models.py", line 960, in save
    await executor.execute_insert(self)
  File "/Users/apple/opt/anaconda3/envs/sanic/lib/python3.9/site-packages/tortoise/backends/base/executor.py", line 226, in execute_insert
    insert_result = await self.db.execute_insert(self.insert_query, values)
  File "/Users/apple/opt/anaconda3/envs/sanic/lib/python3.9/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "/Users/apple/opt/anaconda3/envs/sanic/lib/python3.9/site-packages/tortoise/backends/asyncpg/client.py", line 86, in _translate_exceptions
    raise IntegrityError(exc)
tortoise.exceptions.IntegrityError: null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, 0, 86, 0, null, 0, 0, 2022-10-05 04:39:59.639835+00, 2022-10-05 04:39:59.639953+00).
```

**Expected behavior**

**Additional context**

**Comment by dexax** [comment]
Does this same happens when you also set `generated=False` 
I see in the code that when you set this particular field into pk field,
It auto assumes that this field will be auto generated by DB so it doesn't use provided ddefault
