### ISSUE TITLE
tortoise.exceptions.OperationalError: invalid input for query argument $3: datetime.time(22, 1, 23, 68560, tzinfo=<... ('NoneType' object has no attribute 'days')

### ISSUE THREAD

**Issue by MelodyYuuka** [tortoise/tortoise-orm#1351]
**Describe the bug**
There is a problem using fields.TimeField,
When I set the timezone in Tortoise.init, I get an error inserting a TimeField record.
But if the timezone is not set, no error occurs.

```python
Traceback (most recent call last):
  File "asyncpg\protocol\prepared_stmt.pyx", line 168, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg\protocol\codecs/base.pyx", line 206, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg\protocol\codecs/base.pyx", line 111, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg\pgproto\./codecs/datetime.pyx", line 305, in asyncpg.pgproto.pgproto.timetz_encode
AttributeError: 'NoneType' object has no attribute 'days'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\backends\asyncpg\client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\backends\asyncpg\client.py", line 108, in execute_insert
    return await connection.fetchrow(query, *values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 678, in fetchrow
    data = await self._execute(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 1658, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 1683, in __execute
    return await self._do_execute(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg\protocol\protocol.pyx", line 183, in bind_execute
  File "asyncpg\protocol\prepared_stmt.pyx", line 197, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $1: datetime.time(8, 0, tzinfo=<DstTzInfo 'A... ('NoneType' object has no attribute 'days')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\IDE\project\Python\test.py", line 46, in <module>
    asyncio.run(main())
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "e:\IDE\project\Python\test.py", line 40, in main
    await Test.create(time=time(8, 0, 0))
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\models.py", line 1139, in create
    await instance.save(using_db=db, force_create=True)
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\models.py", line 943, in save
    await executor.execute_insert(self)
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\backends\base\executor.py", line 227, in execute_insert
    insert_result = await self.db.execute_insert(self.insert_query, values)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\backends\base_postgres\client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melody\AppData\Local\Programs\Python\Python311\Lib\site-packages\tortoise\backends\asyncpg\client.py", line 84, in _translate_exceptions
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: invalid input for query argument $1: datetime.time(8, 0, tzinfo=<DstTzInfo 'A... ('NoneType' object has no attribute 'days')
```

**To Reproduce**
```python
from tortoise import Tortoise
from tortoise import fields
from tortoise.connection import connections
from tortoise.models import Model

from datetime import time


class Test(Model):

    time = fields.TimeField()

    class Meta:
        table = "test"


sql_name: str = "postgres"
user: str = "postgres"
password: str = "password"
address: str = "localhost"
port: str = "5432"
database: str = "postgres"


async def connect():
    bind = f"{sql_name}://{user}:{password}@{address}:{port}/{database}"
    # await Tortoise.init(db_url=bind, modules={"models": ["__main__"]})
    await Tortoise.init(db_url=bind, modules={"models": ["__main__"]}, timezone="Asia/Shanghai")
    await Tortoise.generate_schemas()


async def disconnect():
    await connections.close_all()


async def main():
    await connect()
    await Test.create(time=time(8, 0, 0))
    await disconnect()


import asyncio
asyncio.run(main())
```

**Expected behavior**
Insert the record correctly

**Additional context**
Windows11-amd64, CPython==3.11, tortoise==0.19.3

**Comment by MelodyYuuka** [comment]
Looks like an asyncpg problem.
