### ISSUE TITLE
`update_or_create` doesn't seem to work properly

### ISSUE THREAD

**Issue by divadsn** [tortoise/tortoise-orm#1364]
**Describe the bug**
When using `update_or_create` I get the following error:

```
2023-04-02 14:54:01,767 - asyncio - ERROR - Resetting connection with an active transaction <asyncpg.connection.Connection object at 0x000001C0FF9BDEE0>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\David\PycharmProjects\pylife-fastapi\venv\Lib\site-packages\tortoise\models.py", line 1059, in get_or_create
    await cls.select_for_update().filter(**kwargs).using_db(connection).get(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\pylife-fastapi\venv\Lib\site-packages\tortoise\queryset.py", line 1020, in _execute
    raise DoesNotExist("Object does not exist")
tortoise.exceptions.DoesNotExist: Object does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David\PycharmProjects\pylife-fastapi\venv\Lib\site-packages\tortoise\models.py", line 1064, in get_or_create
    return await cls.create(using_db=connection, **defaults, **kwargs), True
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\pylife-fastapi\venv\Lib\site-packages\tortoise\backends\asyncpg\client.py", line 86, in _translate_exceptions
    raise IntegrityError(exc)
tortoise.exceptions.IntegrityError: duplicate key value violates unique constraint "houses_pkey"
DETAIL:  Key (id)=(60) already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\David\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\David\PycharmProjects\pylife-fastapi\venv\Lib\site-packages\pycron\__init__.py", line 24, in run
    asyncio.run(self.function(datetime.now()))
  File "C:\Users\David\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\David\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\pylife-fastapi\mapapylife\worker.py", line 58, in update_houses
    await House.update_or_create(
  File "C:\Users\David\PycharmProjects\pylife-fastapi\venv\Lib\site-packages\tortoise\models.py", line 1113, in update_or_create
    return await cls.get_or_create(defaults, db, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\pylife-fastapi\venv\Lib\site-packages\tortoise\models.py", line 1066, in get_or_create
    return await cls.filter(**kwargs).using_db(connection).get(), False
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\pylife-fastapi\venv\Lib\site-packages\tortoise\backends\asyncpg\client.py", line 88, in _translate_exceptions
    raise TransactionManagementError(exc)
```

**To Reproduce**
```
class House(Model):
    id = fields.IntField(pk=True)
    x = fields.FloatField(null=False)
    y = fields.FloatField(null=False)

await House.create(id=1, x=1.0, y=1.0)  # this will run fine
await House.create_or_update(id=1, x=1.0, y=2.5)  # this should update row ID 1 with new x/y values
```

**Expected behavior**
`update_or_create` should update an existing entry with the same primary key and not throw an error when exists.

**Additional context**
Python: 3.11
Tortoise: 0.19.3

**Comment by divadsn** [comment]
After debugging the code for a while I figured it out. `**kwargs` in this case are used as filter, any new values have to specified in `defaults` argument, which didn't seem obvious when reading the docs. Perhaps this behavior should be changed.
