### ISSUE TITLE
AttributeError: 'int' object has no attribute 'utcoffset'

### ISSUE THREAD

**Issue by gizyatullov** [tortoise/tortoise-orm#1413]
https://tortoise.github.io/query.html#filtering
does not work. how do I find all the records created this month?
now = timezone.now()
        query = (
            await cls._model.filter(
                created_at__year=now.year, created_at__month=now.month
            )
            .annotate(capitalize=Sum("profit"))
            .first()
        )
        return query.capitalize
error AttributeError: 'int' object has no attribute 'utcoffset'

**Comment by gizyatullov** [comment]
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'ami', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
           │         └ <code object <module> at 0x102746660, file "/Users/eric/projects/ami/ami/__main__.py", line 1>
           └ <function _run_code at 0x10274c160>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'ami', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
         └ <code object <module> at 0x102746660, file "/Users/eric/projects/ami/ami/__main__.py", line 1>

  File "/Users/eric/projects/ami/ami/__main__.py", line 20, in <module>
    main()
    └ <function main at 0x10268b0d0>

  File "/Users/eric/projects/ami/ami/__main__.py", line 8, in main
    uvicorn.run(
    │       └ <function run at 0x10353e040>
    └ <module 'uvicorn' from '/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/uvicorn/__init__.py'>

  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()
    │      └ <function Server.run at 0x103535af0>
    └ <uvicorn.server.Server object at 0x104898220>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x103535b80>
           │       │   └ <uvicorn.server.Server object at 0x104898220>
           │       └ <function run at 0x1030bd9d0>
           └ <module 'asyncio' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/__init__.py'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x10488a9c0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x1074c0f10>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d820>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d8...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x1048f1910>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x1074c0f10>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d820>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d8...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d820>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d8...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x1092900a0>
          └ <fastapi.applications.FastAPI object at 0x1048f1910>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x109282ca0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d8...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x109290040>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x1092900a0>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x109282ee0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d8...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x10928bca0>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x109290040>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x109282ee0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d8...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x107538970>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x10928bca0>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x109282ee0>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d8...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x104760670>
          └ APIRoute(path='/api/v1/bot/see', name='trade_completion', methods=['POST'])
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x109282ee0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x10970d8...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x1092825e0>
          └ APIRoute(path='/api/v1/bot/see', name='trade_completion', methods=['POST'])
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x10972be20>
                     └ <function get_request_handler.<locals>.app at 0x109282550>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x10474d1f0>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {}
                 │         └ <function trade_completion at 0x105e4f430>
                 └ <fastapi.dependencies.models.Dependant object at 0x10928b1c0>

  File "/Users/eric/projects/ami/ami/web/api/bot/views.py", line 45, in trade_completion
    return await TradeRepository.monthly_income()
                 │               └ <classmethod object at 0x105e21310>
                 └ <class 'ami.db.repositories.trade.TradeRepository'>

  File "/Users/eric/projects/ami/ami/db/repositories/trade.py", line 55, in monthly_income
    await cls._model.filter(created_at__year=now.year,
          │   │      │                       │   └ <attribute 'year' of 'datetime.date' objects>
          │   │      │                       └ datetime.datetime(2023, 7, 3, 12, 42, 51, 637940, tzinfo=<UTC>)
          │   │      └ <classmethod object at 0x10545c880>
          │   └ <class 'ami.db.models.trade.Trade'>
          └ <class 'ami.db.repositories.trade.TradeRepository'>

  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/queryset.py", line 1000, in __await__
    self._make_query()
    │    └ <function QuerySet._make_query at 0x1054539d0>
    └ <tortoise.queryset.QuerySet object at 0x10941a370>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/queryset.py", line 962, in _make_query
    self.resolve_filters(
    │    └ <function AwaitableQuery.resolve_filters at 0x10544d160>
    └ <tortoise.queryset.QuerySet object at 0x10941a370>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/queryset.py", line 134, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
    │           │    │       │      │     │     └ <member 'basetable' of 'MetaInfo' objects>
    │           │    │       │      │     └ <tortoise.models.MetaInfo object at 0x1055b5b80>
    │           │    │       │      └ <class 'ami.db.models.trade.Trade'>
    │           │    │       └ <class 'ami.db.models.trade.Trade'>
    │           │    └ <function Q.resolve at 0x1053f5430>
    │           └ <tortoise.expressions.Q object at 0x1097505e0>
    └ <tortoise.query_utils.QueryModifier object at 0x10972b8e0>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
           │    │               │      └ Table('trade')
           │    │               └ <class 'ami.db.models.trade.Trade'>
           │    └ <function Q._resolve_kwargs at 0x1053f5310>
           └ <tortoise.expressions.Q object at 0x1097505e0>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/expressions.py", line 321, in _resolve_kwargs
    filter_modifier = self._resolve_regular_kwarg(model, key, value, table)
                      │    │                      │      │    │      └ Table('trade')
                      │    │                      │      │    └ 2023
                      │    │                      │      └ 'created_at__year'
                      │    │                      └ <class 'ami.db.models.trade.Trade'>
                      │    └ <function Q._resolve_regular_kwarg at 0x1053f51f0>
                      └ <tortoise.expressions.Q object at 0x1097505e0>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/expressions.py", line 280, in _resolve_regular_kwarg
    criterion, join = self._process_filter_kwarg(model, key, value, table)
                      │    │                     │      │    │      └ Table('trade')
                      │    │                     │      │    └ 2023
                      │    │                     │      └ 'created_at__year'
                      │    │                     └ <class 'ami.db.models.trade.Trade'>
                      │    └ <function Q._process_filter_kwarg at 0x1053f5160>
                      └ <tortoise.expressions.Q object at 0x1097505e0>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/expressions.py", line 265, in _process_filter_kwarg
    else model._meta.db.executor_class._field_to_db(field_object, value, model)
         │     │     │                              │             │      └ <class 'ami.db.models.trade.Trade'>
         │     │     │                              │             └ 2023
         │     │     │                              └ <tortoise.fields.data.DatetimeField object at 0x10566ef40>
         │     │     └ <property object at 0x10545e6d0>
         │     └ <tortoise.models.MetaInfo object at 0x1055b5b80>
         └ <class 'ami.db.models.trade.Trade'>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/backends/base/executor.py", line 198, in _field_to_db
    return field_object.to_db_value(attr, instance)
           │            │           │     └ <class 'ami.db.models.trade.Trade'>
           │            │           └ 2023
           │            └ <function DatetimeField.to_db_value at 0x1053dc160>
           └ <tortoise.fields.data.DatetimeField object at 0x10566ef40>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/fields/data.py", line 385, in to_db_value
    if timezone.is_naive(value):
       │        │        └ 2023
       │        └ <function is_naive at 0x1053ce0d0>
       └ <module 'tortoise.timezone' from '/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/timezone.py'>
  File "/Users/eric/venvs/ami-GaBHtt_v-py3.9/lib/python3.9/site-packages/tortoise/timezone.py", line 84, in is_naive
    return value.utcoffset() is None
           └ 2023

AttributeError: 'int' object has no attribute 'utcoffset'
