### ISSUE TITLE
how to connect two sqlite3 databases with Tortoise?

### ISSUE THREAD

**Issue by phoenixor** [tortoise/tortoise-orm#1435]
**Describe the bug**
my code need to connect two sqlite3 db, Cookie and Data, whitch separated in two files cookie.sqlite3 and data.sqlite3. i use the official doc code but it did not work
```
async def init_db():
    await Tortoise.init(
        {
            "connections": {
                "first": {
                    "engine": "tortoise.backends.sqlite",
                    "credentials": {"file_path": "/db/cookie.sqlite3"},
                },
                "second": {
                    "engine": "tortoise.backends.sqlite",
                    "credentials": {"file_path": "/db/data.sqlite3"},
                },
            },
            "apps": {
                "cookie": {"models": ["apis.db.models.Cookie"], "default_connection": "first"},
                "data": {"models": ["apis.db.models.Data"], "default_connection": "second"},
            },
        }
    )
    await Tortoise.generate_schemas(safe=True)
```

i have already declaring model apps in class Meta
my main.py looks like this
```
async def main():
    try:
        await init_db()
        # my spider code, whitch need to query cookie in cookie.sqlite3 to crawl data from network and to query data from data.sqlite3
    finally:
        await Profile.close_connection() # close db and http
if __name__ == "__main__":
    asyncio.run(main())
```
when i run main.py in vscode, i got some these
```
Traceback (most recent call last): 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 34, in translate_exceptions_ return await func(self, query, *args) 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 153, in execute_script async with self.acquire_connection() as connection: 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\backends\base\client.py", line 220, in __aenter__ await self.ensure_connection() 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\backends\base\client.py", line 216, in ensure_connection await self.client.create_connection(with_db=True) 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 69, in create_connection await self._connection._connect() 
File "D:\python\py_projects\guardian\venv\lib\site-packages\aiosqlite\core.py", line 137, in _connect self._connection = await future 
File "D:\python\py_projects\guardian\venv\lib\site-packages\aiosqlite\core.py", line 102, in run result = function() 
File "D:\python\py_projects\guardian\venv\lib\site-packages\aiosqlite\core.py", line 397, in connector return sqlite3.connect(loc, **kwargs) 
sqlite3.OperationalError: unable to open database file 

During handling of the above exception, another exception occurred:

Traceback (most recent call last): 
File "d:\python\py_projects\guardian\app\one_search\backend\main.py", line 15, in main await init_db() 
File "d:\python\py_projects\guardian\app\one_search\backend\apis\db\db.py", line 52, in init_db await Tortoise.generate_schemas(safe=True) 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\__init__.py", line 640, in generate_schemas await generate_schema_for_client(connection, safe) 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\utils.py", line 31, in generate_schema_for_client await generator.generate_from_string(schema) 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\backends\base\schema_generator.py", line 448, in generate_from_string await self.client.execute_script(creation_string) 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 36, in translate_exceptions_ raise OperationalError(exc) 
tortoise.exceptions.OperationalError: unable to open database file

During handling of the above exception, another exception occurred: Traceback (most recent call last): 
File "d:\python\py_projects\guardian\app\one_search\backend\main.py", line 33, in <module> asyncio.run(main())) 
File "C:\Python\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) 
File "C:\Python\lib\asyncio\base_events.py", line 641, in run_until_complete return future.result() 
File "d:\python\py_projects\guardian\app\one_search\backend\main.py", line 24, in main await Profile.close_connection() 
File "D:\python\py_projects\guardian\venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 83, in close await self._connection.close() 
File "D:\python\py_projects\guardian\venv\lib\site-packages\aiosqlite\core.py", line 171, in close await self._execute(self._conn.close) 
File "D:\python\py_projects\guardian\venv\lib\site-packages\aiosqlite\core.py", line 67, in _conn raise ValueError("no active connection") 
ValueError: no active connection
```

**To Reproduce**
Steps to reproduce the behavior, preferably a small code snippet.

**Expected behavior**

**Additional context**

**Comment by henadzit** [comment]
@phoenixor are you sure your process has enough permissions to open the database file?

`sqlite3.OperationalError: unable to open database file`

I verified the code that the code works locally. Please feel free to reopen.
