### ISSUE TITLE
Unable to run aerich init-db

### ISSUE THREAD

**Issue by dmto0l2022** [tortoise/tortoise-orm#1448]
**Describe the bug**
Unable to run aerich init-db

**To Reproduce**
see https://github.com/dmto0l2022/basecode/tree/main/fastapi_aerich
I am using aerich for migrations within a podman container

**Expected behavior**
aerich init-db should run and the following error should not arise:

Inited models already, or delete migrations/models and try again.
Traceback (most recent call last):
  File "/env/bin/aerich", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/env/lib/python3.11/site-packages/aerich/cli.py", line 265, in main
    cli()
  File "/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/aerich/cli.py", line 34, in wrapper
    loop.run_until_complete(Tortoise.close_connections())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/tortoise/__init__.py", line 615, in close_connections
    await connections.close_all()
  File "/env/lib/python3.11/site-packages/tortoise/connection.py", line 188, in close_all
    tasks = [conn.close() for conn in self.all()]
                                      ^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/tortoise/connection.py", line 177, in all
    return [self.get(alias) for alias in self.db_config]
                                         ^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/tortoise/connection.py", line 48, in db_config
    raise ConfigurationError(
tortoise.exceptions.ConfigurationError: DB configuration not initialised. Make sure to call Tortoise.init with a valid configuration before attempting to create connections.

**Additional context**
Sadly I have moved across to SQLModel and have been able to get migrations to work successfully.

**Comment by adarshmalviya7** [comment]
Same issue

**Comment by Valt25** [comment]
I have the same issue

> Did you run aerich init first?

I tried it in different ways, however, before running `aerich init-db` command I have pyproject.toml file in current folder, created migrations folted, and migration files themself



> > Did you run aerich init first?
> 
> Also: Do you already have a migrations/models folder present? if so, try delete it and repeat

I tried to delete migrations folder and repeat from `aerich init` command, and it works, however all my migrations was merged in single on, which is not a desired result. What is the trick to delete migrations?

**Comment by Valt25** [comment]
Ok, I understand that init-db is not migrating tool. So if there is already migrations folder, there is no need to recreate it(and yellow message says exactly this). But following exception conveys a completely different message

**Comment by waketzheng** [comment]
> Ok, I understand that init-db is not migrating tool. So if there is already migrations folder, there is no need to recreate it(and yellow message says exactly this). But following exception conveys a completely different message

@Valt25 If migration file exists in migrations/models/ (such as 0_20250514152929_init.py), you just need to run `aerich upgrade`

**Comment by waketzheng** [comment]
> **Describe the bug** Unable to run aerich init-db
> 
> **To Reproduce** see https://github.com/dmto0l2022/basecode/tree/main/fastapi_aerich I am using aerich for migrations within a podman container
> 
> **Expected behavior** aerich init-db should run and the following error should not arise:
> 
> Inited models already, or delete migrations/models and try again. Traceback (most recent call last): File "/env/bin/aerich", line 8, in sys.exit(main()) ^^^^^^ File "/env/lib/python3.11/site-packages/aerich/cli.py", line 265, in main cli() File "/env/lib/python3.11/site-packages/click/core.py", line 1157, in **call** return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/env/lib/python3.11/site-packages/click/core.py", line 1078, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/env/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func return f(get_current_context(), *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/env/lib/python3.11/site-packages/aerich/cli.py", line 34, in wrapper loop.run_until_complete(Tortoise.close_connections()) File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "/env/lib/python3.11/site-packages/tortoise/**init**.py", line 615, in close_connections await connections.close_all() File "/env/lib/python3.11/site-packages/tortoise/connection.py", line 188, in close_all tasks = [conn.close() for conn in self.all()] ^^^^^^^^^^ File "/env/lib/python3.11/site-packages/tortoise/connection.py", line 177, in all return [self.get(alias) for alias in self.db_config] ^^^^^^^^^^^^^^ File "/env/lib/python3.11/site-packages/tortoise/connection.py", line 48, in db_config raise ConfigurationError( tortoise.exceptions.ConfigurationError: DB configuration not initialised. Make sure to call Tortoise.init with a valid configuration before attempting to create connections.
> 
> **Additional context** Sadly I have moved across to SQLModel and have been able to get migrations to work successfully.

Default config file is pyproject.toml, if you have a different filename, don't forget to explicitly declare it: `aerich -c /path/to/your-config-file init-db`

I success to run init-db by the following steps:
```bash
git clone https://github.com/dmto0l2022/basecode/
cd archive/fastapi_aerich/
python3.9 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
pip install -U pydantic cryptography tomlkit
cd app/
rm migrations/models/file.txt
aerich -c pyproject1.toml init-db
```
Output is:
```
Success creating app migration folder migrations/models
Success generating initial migration file for app "models"
```
cat migrations/models/0*
```
from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS `event` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
```
