### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 0: invalid start byte

### ISSUE THREAD

**Issue by protector131090** [tortoise/tortoise-orm#1475]
[Training] [2023-09-10T10:35:43.844207] WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
[Training] [2023-09-10T10:35:43.844207] CUDA SETUP: Loading binary C:\Voiceclonetortoise\ai-voice-cloning\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
[Training] [2023-09-10T10:35:43.844207] Disabled distributed training.
[Training] [2023-09-10T10:35:43.844207] Loading from ./models/tortoise/dvae.pth
[Training] [2023-09-10T10:35:43.845367] Traceback (most recent call last):
[Training] [2023-09-10T10:35:43.845367]   File "C:\Voiceclonetortoise\ai-voice-cloning\src\train.py", line 64, in <module>
[Training] [2023-09-10T10:35:43.845367]     train(config_path, args.launcher)
[Training] [2023-09-10T10:35:43.845367]   File "C:\Voiceclonetortoise\ai-voice-cloning\src\train.py", line 31, in train
[Training] [2023-09-10T10:35:43.845367]     trainer.do_training()
[Training] [2023-09-10T10:35:43.845367]   File "c:\voiceclonetortoise\ai-voice-cloning\modules\dlas\dlas\train.py", line 408, in do_training
[Training] [2023-09-10T10:35:43.846367]     metric = self.do_step(train_data)
[Training] [2023-09-10T10:35:43.846367]   File "c:\voiceclonetortoise\ai-voice-cloning\modules\dlas\dlas\train.py", line 271, in do_step
[Training] [2023-09-10T10:35:43.846367]     gradient_norms_dict = self.model.optimize_parameters(
[Training] [2023-09-10T10:35:43.846367]   File "c:\voiceclonetortoise\ai-voice-cloning\modules\dlas\dlas\trainer\ExtensibleTrainer.py", line 321, in optimize_parameters
[Training] [2023-09-10T10:35:43.846367]     ns = step.do_forward_backward(
[Training] [2023-09-10T10:35:43.847368]   File "c:\voiceclonetortoise\ai-voice-cloning\modules\dlas\dlas\trainer\steps.py", line 242, in do_forward_backward
[Training] [2023-09-10T10:35:43.847368]     local_state[k] = v[grad_accum_step]
[Training] [2023-09-10T10:35:43.847842] IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Voiceclonetortoise\ai-voice-cloning\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Voiceclonetortoise\ai-voice-cloning\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Voiceclonetortoise\ai-voice-cloning\venv\lib\site-packages\gradio\blocks.py", line 898, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Voiceclonetortoise\ai-voice-cloning\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Voiceclonetortoise\ai-voice-cloning\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Voiceclonetortoise\ai-voice-cloning\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Voiceclonetortoise\ai-voice-cloning\venv\lib\site-packages\gradio\utils.py", line 549, in async_iteration
    return next(iterator)
  File "C:\Voiceclonetortoise\ai-voice-cloning\src\utils.py", line 1995, in run_training
    for line in iter(training_state.process.stdout.readline, ""):
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 0: invalid start byte

**Comment by protector131090** [comment]
how do i fix it?

**Comment by panla** [comment]
@protector131090 
See the error message, It's not tortoise-orm`s fault
