### ISSUE TITLE
数据库字段设置null=True时，通过pydantic_model_creator还是要必填

### ISSUE THREAD

**Issue by JimiyLW** [tortoise/tortoise-orm#1516]
**Describe the bug**
数据库字段设置null=True时，通过pydantic_model_creator还是要必填。

**To Reproduce**
```
class MyTable(Model):
    name = fields.CharField(max_length=255, description='名称')
    cancel_time = fields.DatetimeField(description='取消时间', default=None, null=True)

MyTableModel = pydantic_model_creator(MyTable, name='MyTable', exclude_readonly=True, model_config=model_config)
MyTableModel(name="abc")  # raise ValidationError
```

**Expected behavior**
对于tortoise-orm中允许为空的字段，创建Pydantic对象应该对该字段允许为空

**Additional context**
我当前在自己本地修改的方式：
```
        if fname in properties and not isinstance(properties[fname], tuple):
            fconfig["title"] = fname.replace("_", " ").title()
            description = comment or _br_it(fdesc.get("docstring") or fdesc["description"] or "")
            if description:
                fconfig["description"] = description
            ftype = properties[fname]
            if isinstance(ftype, PydanticDescriptorProxy):
                continue
            # if field_default is not None and not callable(field_default):   # 初始写法
            if (fdesc.get("nullable") or field_default is not None) and not callable(field_default):  # 改进写法
                properties[fname] = (ftype, Field(default=field_default, **fconfig))
            else:
                properties[fname] = (ftype, Field(**fconfig))
```

**Comment by JimiyLW** [comment]
我的解决方案是在`site-packages\tortoise\contrib\pydantic\creator.py`文件的的第410行修改了判断条件：
```python
# if field_default is not None and not callable(field_default):   # 之前的
 if (fdesc.get("nullable") or field_default is not None) and not callable(field_default):    # 我修改后的
```
```
> pip show tortoise-orm
Name: tortoise-orm
Version: 0.20.0
Summary: Easy async ORM for python, built with relations in mind
Home-page: https://github.com/tortoise/tortoise-orm
Author: Andrey Bondar
Author-email: andrey@bondar.ru
License: Apache-2.0
Location: d:\users\workspace\venv_my\vent_fastapi\lib\site-packages
Requires: aiosqlite, iso8601, pypika-tortoise, pytz
Required-by:
```

> 我遇到相似的问题 I encountered a similar problem.
> 
> 代码示例 example
> 
> ```python
> from tortoise import fields, models
> from tortoise.contrib.pydantic import pydantic_model_creator
> 
> 
> class Todo(models.Model):
>     create_datetime = fields.DatetimeField(auto_now_add=True)
> 
> 
> TodoIn = pydantic_model_creator(
>     Todo,
>     name="TodoIn",
>     exclude=("user", "user_id"),
>     exclude_readonly=True,
> )
> 
> TodoIn()
> ```
> 
> 执行结果 result
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\admin\PycharmProjects\v2\aaaa.py", line 15, in <module>
>     TodoIn()
>   File "C:\Users\admin\PycharmProjects\v2\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
>     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
> pydantic_core._pydantic_core.ValidationError: 1 validation error for TodoIn
> create_datetime
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.4/v/missing
> ```
> 
> ```
> >pip show tortoise-orm
> Name: tortoise-orm
> Version: 0.20.0
> Summary: Easy async ORM for python, built with relations in mind
> Home-page: https://github.com/tortoise/tortoise-orm
> ```

**Comment by dongfangtianyu** [comment]
分享我的临时修复方案。在下面插入新的代码，补充字段参数
Share my temporary fix plan. Insert new code below to supplement field parameters


https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/contrib/pydantic/creator.py#L405


```python
        # bugfix: missing some parameter
        for k, v in fdesc.items():
            if v in [True, False, None] and k not in fconfig:
                fconfig[k]=v
```

**Comment by john2023wick** [comment]
在我使用pdm安装tortoise-orm中，我也遇到了这个情况。
然后我克隆了tortoise-orm项目的main分支最新源码，运行其中的例子，测试发现这个问题已经被修复

While using pdm to install tortoise-orm, I encountered this issue. 
Then, I cloned the latest source code from the main branch of the tortoise-orm project and ran the examples in it. 
The tests showed that this issue has been fixed.
