### ISSUE TITLE
timezone bug

### ISSUE THREAD

**Issue by nuanxinqing123** [tortoise/tortoise-orm#1543]
**Describe the bug**
When I set the time zone to the above, I got +16, which caused an error in MySQL

**To Reproduce**
'timezone': 'America/Los_Angeles'

**Expected behavior**

**Additional context**
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/tortoise/backends/mysql/client.py", line 129, in create_connection
    await cursor.execute(f"SET SESSION time_zone='{tz}';")
  File "asyncmy/cursors.pyx", line 179, in execute
  File "asyncmy/cursors.pyx", line 364, in _query
  File "asyncmy/connection.pyx", line 494, in query
  File "asyncmy/connection.pyx", line 682, in _read_query_result
  File "asyncmy/connection.pyx", line 1069, in read
  File "asyncmy/connection.pyx", line 644, in read_packet
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
  File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
asyncmy.errors.OperationalError: (1298, "Unknown or incorrect time zone: '+16:00'")

**Comment by liqiang-github** [comment]
any comment? I run into the same issue

**Comment by nuanxinqing123** [comment]
> 有什么评论吗？我也遇到了同样的问题

The way I solved it was to set the timezone to utc, and then based on the user's locale (e.g. Asia/Shanghai), calculate the conversion at the code level.

**Comment by liqiang-github** [comment]
Thanks for reply. I will give a try.
