### ISSUE TITLE
Tortoise crashes when used with Vercel and FastAPI

### ISSUE THREAD

**Issue by Thytu** [tortoise/tortoise-orm#1684]
**Describe the bug**
Tortoise seems to crash when used with Vercel (and probably any serverless service) + FastAPI.

When using `tortoise-orm` with FastAPI and Vercel, tortoise cannot manage to fetch the database connection resulting in the following error:

```
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 315, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 215, in __call__
    asyncio.run(self.run_asgi_instance(asgi_instance))
  File "/var/lang/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/var/lang/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/var/lang/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
  File "/var/task/vc__handler__python.py", line 219, in run_asgi_instance
    await asgi_instance
  File "/var/task/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/var/task/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/var/task/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/var/task/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/var/task/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/var/task/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/var/task/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/var/task/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/var/task/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/var/task/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/var/task/Manager/main.py", line 48, in some_example
    await Video.all() # KO
  File "/var/task/tortoise/models.py", line 1262, in all
    return cls._db_queryset(using_db)
  File "/var/task/tortoise/models.py", line 1063, in _db_queryset
    db = using_db or cls._choose_db(for_write)
  File "/var/task/tortoise/models.py", line 1011, in _choose_db
    db = router.db_for_read(cls)
  File "/var/task/tortoise/router.py", line 36, in db_for_read
    return self._db_route(model, "db_for_read")
  File "/var/task/tortoise/router.py", line 31, in _db_route
    return connections.get(self._router_func(model, action))
  File "/var/task/tortoise/router.py", line 18, in _router_func
    for r in self._routers:
```

**To Reproduce**
Here is the code-snippet to reproduce it:
```py
# app/main.py
from fastapi import FastAPI
from tortoise import Tortoise
from contextlib import asynccontextmanager
from Manager.db.database import _get_db_config
from tortoise.contrib.fastapi import RegisterTortoise
from tortoise import models, fields



class SomeTable(models.Model):
    id = fields.IntField(pk=True)


@asynccontextmanager
async def lifespan(app: FastAPI):
    async with RegisterTortoise(
        app=app,
        config=_get_db_config(),
        generate_schemas=True,
        add_exception_handlers=True,
    ):
        yield

    await Tortoise.close_connections()


app = FastAPI(lifespan=lifespan)


@app.get("/some-example")
async def some_example():
    await SomeTable.all() # TypeError: 'NoneType' object is not iterable
    return "some expected response"


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
```

Obviously, in order to reproduce the error one also needs to deploy it on Vercel :)

**Expected behavior**
I would expect tortoise to use previously initialized connection to return every elements of `SomeTable`.

**Additional context**
Note that in order to debug I also tried the following, which also results in a crash. However this time it crashs at the second call to the database as it tried to close an event loop that no-longer exists, resulting in a `RuntimeError('Event loop is closed')` error.

```py
# app/main.py
from fastapi import FastAPI
from tortoise import Tortoise
from contextlib import asynccontextmanager
from Manager.db.database import _get_db_config
from tortoise.contrib.fastapi import RegisterTortoise
from tortoise import models, fields



class SomeTable(models.Model):
    id = fields.IntField(pk=True)


async def init_db():
    await Tortoise.init(config=YOUR_CONFIG_HERE)
    await Tortoise.generate_schemas()


app = FastAPI()


@app.get("/some-example")
async def some_example():
    await init_db() # First call works
    # second calls fail with `raise RuntimeError('Event loop is closed')``
    await SomeTable.all()
    return "some expected response"


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
```

**Comment by Thytu** [comment]
Update: I found this temporary fix, however I'll obviously need to find a better option :D

```py
@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    await init_db() # already in the previous snippet

    response = await call_next(request)

    await Tortoise.close_connections() # Now also close the session after each call

    return response
```

**Comment by igoncharov85** [comment]
I'm having the same issue. Did anyone was able to fix it somehow?

**Comment by henadzit** [comment]
@igoncharov85 could you please post your full stack trace?

**Comment by igoncharov85** [comment]
@henadzit thank you for trying to help with this issue.

This is the last part and full stack is here - https://tt-rc.sentry.io/share/issue/f2af9d3131bd43868c2e9113c0cf9eb8/
```
asyncpg/protocol/protocol.pyx in asyncpg.protocol.protocol.BaseProtocol.abort at line 608

Set up Code Mapping
In App

        if self.closing:
            return
        self.closing = True
        self._handle_waiter_on_connection_lost(None)
        self._terminate()
        self.transport.abort()
        self.transport = None
    @cython.iterable_coroutine
    async def close(self, timeout):
        if self.closing:
```

I followed the last best practice how to marry Fast API + Tortoise ORM.
I want to use background tasks in my app so in the code below it reproduces the issue in my production.

I'm trying to offload some work with database after request is completed to background_tasks
background_tasks.add_task(save_ping_history, request_obj.client.host)

If you deploy to Vercel and point to database and start it, try calling /ping from the swagger.
Every 2nd request fails with the error above.
Locally it works as it should as well.
There is something wrong with tortoise used in background tasks or Vercel runtime or I'm missing something...
I tried deploying the same code to Render.com and it works fine without adjustments. 

```
import os
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
import logging

import sentry_sdk
from dotenv import load_dotenv
from fastapi import FastAPI, Request, BackgroundTasks
from pydantic import BaseModel
from starlette.middleware.cors import CORSMiddleware
from starlette.responses import Response
from tortoise import fields, Tortoise
from tortoise.models import Model
from tortoise.contrib.fastapi import register_tortoise

logger = logging.getLogger(__name__)
load_dotenv()

DATABASE_URL = os.getenv("POSTGRES_URL_NO_SSL")
SENTRY_DSN = os.getenv("SENTRY_DSN")
VERCEL_TARGET_ENV = os.getenv("VERCEL_TARGET_ENV", "LOCAL_RUN")

TORTOISE_CONFIG = {
    "connections": {"default": DATABASE_URL},
    "apps": {
        "models": {
            "models": ["app"],
            "default_connection": "default",
        },
    },
    "use_tz": False,
    "timezone": "UTC"
}


def register_orm(fast_app: FastAPI):
    register_tortoise(
            fast_app,
            TORTOISE_CONFIG,
            generate_schemas=True,
            add_exception_handlers=True,
        )


@asynccontextmanager
async def lifespan(fast_api_app: FastAPI) -> AsyncGenerator[None, None]:
    # app startup
    register_orm(fast_api_app)
    yield
    # db connections closed
    await Tortoise.close_connections()

app = FastAPI(lifespan=lifespan, docs_url="/")

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        send_default_pii=True,
        traces_sample_rate=0,
        environment=VERCEL_TARGET_ENV
    )

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Vercel is not able to process db request without it
@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    await Tortoise.init(TORTOISE_CONFIG)
    try:
        response = await call_next(request)
    except Exception as ex:
        logger.exception(ex)
        return Response("Internal server error", status_code=500)
    finally:
        await Tortoise.close_connections()
    return response


@app.middleware("http")
async def catch_exceptions_middleware(request: Request, call_next):
    try:
        return await call_next(request)
    except Exception as ex:
        logger.exception(ex)
        return Response("Internal server error", status_code=500)


class PingHistory(Model):
    Id = fields.IntField(pk=True)
    IPAddress = fields.CharField(max_length=50, null=True)
    CreatedAt = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "PingHistory"


class PingRequest(BaseModel):
    SaveAsync: bool = True


@app.post("/ping")
async def ping(fast_request: Request, request: PingRequest, background_tasks: BackgroundTasks):
    background_tasks.add_task(save_ping_history, request.SaveAsync, fast_request.client.host)
    return {"message": "pong!"}


async def save_ping_history(save_async: bool, ip_address):
    logger.warning("Starting to save Ping History")
    if save_async:
        await PingHistory.create(IPAddress=ip_address)
    logger.warning("Saved Ping History")


@app.get("/history")
async def ping_history(request_obj: Request):
    history = await PingHistory.filter(IPAddress=request_obj.client.host).order_by("-CreatedAt").offset(0).limit(20)
    data = [{"Id": item.Id, "IPAddress": item.IPAddress, "CreatedAt": item.CreatedAt} for item in history]
    return {"data": data}
```

You can try deploying this repo to Vercel or Render specifying POSTGRES_URL_NO_SSL keyword.

https://github.com/igoncharov85/vercel-tortoise

Thanks!
