### ISSUE TITLE
Sanic example is not working

### ISSUE THREAD

**Issue by Seruojka** [tortoise/tortoise-orm#199]
I get an error when starting tortoise-orm along with Sanic as an example
Python 3.6 from this source [https://github.com/tortoise/tortoise-orm/blob/develop/examples/sanic/main.py](url)
1 - I installed everything according to the instructions. The package required installation separately
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/Sergey/Desktop/Projects/rush-sanic/main.py", line 5, in <module>
    from tortoise.contrib.sanic import register_tortoise
  File "/Users/Sergey/Desktop/Projects/rush-sanic/venv/lib/python3.6/site-packages/tortoise/contrib/sanic/__init__.py", line 6, in <module>
    from tortoise import Tortoise
ImportError: cannot import name 'Tortoise'
```

2 - After install Tortoise separetly i have another problem:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/Sergey/Desktop/Projects/rush-sanic/main.py", line 46, in <module>
    port=app.config.PORT
  File "/Users/Sergey/Desktop/Projects/rush-sanic/venv/lib/python3.6/site-packages/sanic/app.py", line 1135, in run
    serve(**server_settings)
  File "/Users/Sergey/Desktop/Projects/rush-sanic/venv/lib/python3.6/site-packages/sanic/server.py", line 775, in serve
    trigger_events(before_start, loop)
  File "/Users/Sergey/Desktop/Projects/rush-sanic/venv/lib/python3.6/site-packages/sanic/server.py", line 633, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/Users/Sergey/Desktop/Projects/rush-sanic/venv/lib/python3.6/site-packages/tortoise/contrib/sanic/__init__.py", line 78, in init_orm
    await Tortoise.init(config=config, config_file=config_file, db_url=db_url, modules=modules)
AttributeError: type object 'Tortoise' has no attribute 'init'
```
**type object 'Tortoise' has no attribute 'init'**

![image](https://user-images.githubusercontent.com/14239516/65715980-426f4d80-e0af-11e9-8bab-95c97272774f.png)

**Comment by Seruojka** [comment]
I forgot to indicate that there are still errors in the example.
module in models.py is not imported correctly

in example:
```
from tortoise import Model, fields
class Users(Model):
```

right:
```
from tortoise import models, fields
class Users(models.Model):
```

**Comment by grigi** [comment]
Thanks for bringing attention to the lacking example/integration. (It does need some work it seems)

Whilst `from tortoise import Model, fields` is bad form, it does work. Also `Tortoise.init(…)` definitely exists.

I just tested the example manually right now, and it booted for me:
```
<create py3.6 venv>
pip install tortoise-orm sanic
<copy main.py & models.py from sanic folder into local folder>
python main.py
<curled http://127.0.0.1/ in another terminal>
```

And this is what I saw:
```
[2019-09-27 00:34:59 +0200] [14067] [INFO] Goin' Fast @ http://127.0.0.1:5000
INFO:sanic.root:Goin' Fast @ http://127.0.0.1:5000
INFO:tortoise:Tortoise-ORM startup
    connections: {'default': {'engine': 'tortoise.backends.sqlite', 'credentials': {'journal_mode': 'WAL', 'journal_size_limit': 16384, 'file_path': ':memory:'}}}
    apps: {'models': {'models': ['models'], 'default_connection': 'default'}}
DEBUG:aiosqlite:executing functools.partial(<function connect.<locals>.connector at 0x7f331ee45f28>)
DEBUG:aiosqlite:returning <sqlite3.Connection object at 0x7f3320023490>
DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f3320023490>, 'PRAGMA journal_mode=WAL', [])
DEBUG:aiosqlite:returning <sqlite3.Cursor object at 0x7f331ebdeb20>
DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7f331ebdeb20>)
DEBUG:aiosqlite:returning None
DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7f3320023490>, 'PRAGMA journal_size_limit=16384', [])
DEBUG:aiosqlite:returning <sqlite3.Cursor object at 0x7f331ebdec00>
DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7f331ebdec00>)
DEBUG:aiosqlite:returning None
DEBUG:db_client:Created connection <Connection(Thread-1, started 139857499055872)> with params: filename=:memory: journal_mode=WAL journal_size_limit=16384
INFO:root:Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7f331ee504e0>}, {'models': {'Users': <class 'models.Users'>}}
INFO:root:Tortoise-ORM generating schema
DEBUG:tortoise:Creating schema: CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(50) NOT NULL
);
DEBUG:db_client:CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(50) NOT NULL
);
DEBUG:aiosqlite:executing functools.partial(<built-in method executescript of sqlite3.Connection object at 0x7f3320023490>, 'CREATE TABLE IF NOT EXISTS "users" (\n    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n    "name" VARCHAR(50) NOT NULL\n);')
DEBUG:aiosqlite:returning <sqlite3.Cursor object at 0x7f331ebdec00>
[2019-09-27 00:34:59 +0200] [14067] [INFO] Starting worker [14067]
INFO:sanic.root:Starting worker [14067]
DEBUG:db_client:SELECT "id","name" FROM "users": None
DEBUG:aiosqlite:executing functools.partial(<bound method Connection._execute_fetchall of <Connection(Thread-1, started 139857499055872)>>, 'SELECT "id","name" FROM "users"', [])
DEBUG:aiosqlite:returning []
[2019-09-27 00:35:05 +0200] - (sanic.access)[INFO][127.0.0.1:52468]: GET http://127.0.0.1:5000/  200 12
INFO:sanic.access:
^C[2019-09-27 00:35:51 +0200] [14067] [INFO] Stopping worker [14067]
INFO:sanic.root:Stopping worker [14067]
DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x7f3320023490>)
DEBUG:aiosqlite:returning None
DEBUG:db_client:Closed connection <Connection(Thread-1, started 139857499055872)> with params: filename=:memory: journal_mode=WAL journal_size_limit=16384
INFO:tortoise:Tortoise-ORM shutdown
INFO:root:Tortoise-ORM shutdown
[2019-09-27 00:35:51 +0200] [14067] [INFO] Server Stopped
INFO:sanic.root:Server Stopped
```

Is your environment set up correctly? What OS are you using? (I did this on Linux)

**Comment by Seruojka** [comment]
hi! thanks for the quick response! 
I'm using osx and trying to connect to a postgres database. forgot to specify this.

**Comment by Seruojka** [comment]
Friend, I'm very sorry.
I finally got enough sleep and realized that I had a mistake while installing orm.
I started an empty project, deleted all unnecessary dependencies and it worked;)
Thank you very much for spending your time on me!

**Comment by bestenevoy** [comment]
Why do I need to install `Tortoise` separately
