### ISSUE TITLE
AttributeError when trying to order_by DatetimeField

### ISSUE THREAD

**Issue by bbedward** [tortoise/tortoise-orm#247]
I have the models:

```py
class User(Model):
    id = fields.BigIntField(pk=True, generated=False)
    name = fields.CharField(max_length=50)
    created_at = fields.DatetimeField(auto_now_add=True)
    modified_at = fields.DatetimeField(auto_now=True)

    class Meta:
        table = "users"
```

and

```py
class Transaction(Model):
    id = fields.UUIDField(pk=True)
    sending_user = fields.ForeignKeyField('db.User', related_name='sent_transactions', index=True)
    receiving_user = fields.ForeignKeyField('db.User', related_name='received_transactions', null=True, index=True)
    destination = fields.CharField(max_length=65)
    block_hash = fields.CharField(max_length=64, index=True, null=True)
    amount = fields.CharField(max_length=50)
    created_at = fields.DatetimeField(auto_now_add=True, index=True)
    modified_at = fields.DatetimeField(auto_now=True)
    retries = 0

    class Meta:
        table = 'transactions'
```

I'm getting this exception when attempting a query: `AttributeError: type object 'Transaction' has no attribute 'created_at'`

I've tried some variations of the query and they're all getting the same error

First variation:
```py
user = await User.filter(id=1).first()
last_withdraw = await user.sent_transactions.filter(created_at__gt=datetime.datetime.utcnow() - datetime.timedelta(seconds=300)).all().order_by('-created_at').limit(1)
```
Second variation:
```py
user = await User.filter(id=1).first()
last_withdraw = await user.sent_transactions.filter(created_at__gt=datetime.datetime.utcnow() - datetime.timedelta(seconds=300)).order_by('-created_at').first()
```
Third variation:
```py
user = await User.filter(id=1).first()
last_withdraw = await Transaction.filter(user=user, created_at__gt=datetime.datetime.utcnow() - datetime.timedelta(seconds=300)).order_by('-created_at').first()
```

Here's the full stack trace
```
Traceback (most recent call last):
  File "/home/tipbot/test_bot/cogs/account.py", line 73, in cog_before_invoke
    withdraw_delay = await user.get_next_withdraw_s()
  File "/home/tipbot/test_bot/db/models/user.py", line 114, in get_next_withdraw_s
    last_withdraw = await self.sent_transactions.filter(created_at__gt=datetime.datetime.utcnow() - datetime.timedelta(seconds=Constants.WITHDRAW_COOLDOWN)).order_by('-created_at').first()
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/queryset.py", line 508, in __await__
    self._make_query()
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/queryset.py", line 495, in _make_query
    custom_filters=self._custom_filters,
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/queryset.py", line 61, in resolve_filters
    modifier &= node.resolve(model, annotations, custom_filters)
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/query_utils.py", line 304, in resolve
    return self._resolve_kwargs(model)
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/query_utils.py", line 277, in _resolve_kwargs
    filter_modifier = self._resolve_regular_kwarg(model, key, value)
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/query_utils.py", line 237, in _resolve_regular_kwarg
    criterion, join = _process_filter_kwarg(model, key, value)
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/query_utils.py", line 35, in _process_filter_kwarg
    else model._meta.db.executor_class._field_to_db(field_object, value, model)
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/backends/base/executor.py", line 106, in _field_to_db
    return cls.TO_DB_OVERRIDE[field_object.__class__](field_object, attr, instance)
  File "/home/tipbot/test_bot/venv/lib/python3.7/site-packages/tortoise/backends/sqlite/executor.py", line 33, in to_db_datetime
    if self.auto_now_add and getattr(instance, self.model_field_name) is None:
AttributeError: type object 'Transaction' has no attribute 'created_at'
```

Sorry for bugging you so much lately, I'm just at a bit of a loss on this issue.

**Edit**

This works as expected and for my purposes accomplishes the same thing, but curious as to why it doesn't work with the `.filter()` method

```py
await self.sent_transactions.all().order_by('-created_at').first()
```

**Comment by grigi** [comment]
This seems to be the same issue as #248 
Will add it to the CI to ensure that it works everywhere, and stays working.

Please leave this open until I have this all in the CI.

**Comment by bbedward** [comment]
0.15.2 did indeed fix my problem
