### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode' with asyncpg

### ISSUE THREAD

**Issue by prostomarkeloff** [tortoise/tortoise-orm#254]
**Describe the bug**
Application doesn't start with asyncpg and `generate_schemas` param.

```py

ERROR:uvicorn.error:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 473, in __call__
    await self.startup()
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 457, in startup
    await handler()
  File "/usr/local/lib/python3.7/site-packages/tortoise/contrib/starlette/__init__.py", line 80, in init_orm
    await Tortoise.generate_schemas()
  File "/usr/local/lib/python3.7/site-packages/tortoise/__init__.py", line 682, in generate_schemas
    await generate_schema_for_client(connection, safe)
  File "/usr/local/lib/python3.7/site-packages/tortoise/utils.py", line 16, in generate_schema_for_client
    await generator.generate_from_string(schema)
  File "/usr/local/lib/python3.7/site-packages/tortoise/backends/base/schema_generator.py", line 374, in generate_from_string
    await self.client.execute_script(creation_string)
  File "/usr/local/lib/python3.7/site-packages/tortoise/backends/asyncpg/client.py", line 33, in translate_exceptions_
    return await func(self, *args)
  File "/usr/local/lib/python3.7/site-packages/tortoise/backends/asyncpg/client.py", line 173, in execute_script
    await connection.execute(query)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 272, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 316, in query
  File "asyncpg/protocol/protocol.pyx", line 807, in asyncpg.protocol.protocol.BaseProtocol._dispatch_result
  File "asyncpg/protocol/protocol.pyx", line 734, in asyncpg.protocol.protocol.BaseProtocol._on_result__simple_query
AttributeError: 'NoneType' object has no attribute 'decode'

[2019-11-29 12:02:31 +0000] [37] [ERROR] Application startup failed. Exiting.
{"loglevel": "info", "workers": 1, "bind": "0.0.0.0:8080", "workers_per_core": 1.0, "host": "0.0.0.0", "port": "8080"}
ERROR:uvicorn.error:Application startup failed. Exiting.
[2019-11-29 12:02:31 +0000] [37] [INFO] Worker exiting (pid: 37)
```

**To Reproduce**
```py
DB_MODELS = ["app.models.db.tortoise"]
DB_CONFIG = {
    'connections': {
        'default': {
            'engine': 'tortoise.backends.asyncpg',
            'credentials': {
                'host': 'postgres',
                'port': '5432',
                'user': 'postgres',
                'password': 'postgres',
                'database': 'mydb',
            }
        },
    },
    'apps': {
        'models': {
            'models': DB_MODELS,
            'default_connection': 'default',
        }
    }
}

def init_db(app: FastAPI):
    register_tortoise(
        app, generate_schemas=True, config=DB_CONFIG
    )
```

**NOTE**: Folder that should contain the models `app.models.db.tortoise` is empty (except `__init__.py` file.)

**Expected behavior**
I think application should start :smile:

**Comment by prostomarkeloff** [comment]
UPD: as notes @hyzyla in [this](https://github.com/MagicStack/asyncpg/issues/240#issuecomment-539449476) issue, it may happen if you will insert a lot of values

**Comment by grigi** [comment]
Man, this is troublesome. is the schema it generates particularily large? Does it happen consistently?
I'm wondering if we should issue a separate query for each table instead of one large one with all of them?

**Comment by prostomarkeloff** [comment]
> Man, this is troublesome. is the schema it generates particularily large? Does it happen consistently?
> I'm wondering if we should issue a separate query for each table instead of one large one with all of them?

I forgot say that i **dont'** define any models.

**Comment by grigi** [comment]
Well, you could try setting `generate_schemas=False`.
I never tried setup without a model... Will have to test that to see what it does?

**Comment by prostomarkeloff** [comment]
OK. I have found the problem. Try run schema generation without any defined models. With 1 or more defined models i might avoid this behaviour.

**Comment by prostomarkeloff** [comment]
Can we do smth for it? I think it may be problem for newcomers.

**Comment by grigi** [comment]
You mean don't do a generate_schema if there is nothing to generate? Yes, I can do that.

**Comment by AEnterprise** [comment]
can it also log a warning or so, cause this might indicate someone loading the wrong file by accident

**Comment by grigi** [comment]
Thats a good idea

**Comment by grigi** [comment]
Please test v0.15.4

It now emits a `RuntimeWarning` when a module has no models to import, and should not crash like OP, please test :smile: 
```
/home/grigi/coding/tortoise/tortoise/contrib/starlette/__init__.py:76: RuntimeWarning: Module "models" has no models
  await Tortoise.init(config=config, config_file=config_file, db_url=db_url, modules=modules)
```

**Comment by prostomarkeloff** [comment]
Thanks so much! I have tested it and it works awesome!

**Comment by ZachSARAO** [comment]
This also seems to be a problem if I try to run an empty sql file

```py
await connection.execute_script("")
```
