### ISSUE TITLE
Count records with filter by an annotated field fails due to invalid SQL generation

### ISSUE THREAD

**Issue by mirrorrim** [tortoise/tortoise-orm#469]
**Describe the bug**
When I try to filter out conversations without messages there is missing JOIN in generated SQL, but everything is ok without count.

**To Reproduce**
```python
from tortoise import Tortoise, fields, run_async
from tortoise.functions import Count
from tortoise.models import Model


class Conversation(Model):
    id = fields.IntField(pk=True)
    messages: fields.ReverseRelation["Message"]


class Message(Model):
    id = fields.IntField(pk=True)
    conversation: fields.ForeignKeyRelation["Conversation"] = fields.ForeignKeyField(
        "models.Conversation", on_delete=fields.CASCADE, related_name="messages"
    )
    text = fields.TextField()


async def main():
    await Tortoise.init(db_url="sqlite://:memory:", modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()

    c1 = await Conversation.create(id=1)
    c2 = await Conversation.create(id=2)

    m1 = await Message.create(id=1, conversation=c1, text="message 1")
    m2 = await Message.create(id=2, conversation=c1, text="message 2")
    m3 = await Message.create(id=3, conversation=c1, text="message 3")

    queryset = Conversation.annotate(messages_count=Count("messages")).filter(messages_count__gt=0)

    print(queryset.sql())
    # Output:
    # SELECT "conversation"."id", COUNT("message"."id") "messages_count"
    # FROM "conversation"
    #    LEFT OUTER JOIN "message" ON "conversation"."id" = "message"."conversation_id"
    # GROUP BY "conversation"."id"
    # HAVING COUNT("message"."id") > 0

    print(queryset.count().sql())
    # Output:
    # SELECT COUNT(*) FROM "conversation" HAVING COUNT("id")>0


if __name__ == "__main__":
    run_async(main())

```

**Expected behavior**
No error, 1 as result

**Additional context**
I use PostgeSQL for my project, but I've used sqlite for code snippet. Almost the same code and the output:

```sql
-- select my conversations
SELECT "conversation"."id",
       "conversation"."type",
       "conversation"."created_at",
       "conversation"."updated_at",
       COUNT("message"."id") "messages_count"
FROM "conversation"
         LEFT OUTER JOIN "message" ON "conversation"."id" = "message"."conversation_id"
         LEFT OUTER JOIN "membership" ON "conversation"."id" = "membership"."conversation_id"
WHERE "membership"."user_id" = '01738bfb-d0ea-3b1b-3042-7ee656986c6d'
GROUP BY "conversation"."id"
HAVING NOT COUNT("message"."id") = 0;

-- select count of conversations - missed "message" JOIN
SELECT COUNT(*)
FROM "conversation"
         LEFT OUTER JOIN "membership" ON "conversation"."id" = "membership"."conversation_id"
WHERE "membership"."user_id" = '01738bfb-d0ea-3b1b-3042-7ee656986c6d'
HAVING NOT COUNT("message"."id") = 0;

```

**Comment by mirrorrim** [comment]
I found out that if I add an additional filter for messages everything works fine.

```python
conversations_couint = (
    await Conversation.annotate(messages_count=Count("messages"))
    .filter(messages_count__gt=0)
    .exclude(messages__id="00000000-0000-0000-0000-000000000000")
    .count()
)
```

Result SQL:
```sql
SELECT COUNT(*)
FROM "conversation"
         LEFT OUTER JOIN "message" ON "conversation"."id" = "message"."conversation_id"
WHERE NOT "message"."id" = '00000000-0000-0000-0000-000000000000'
HAVING COUNT("message"."id") > 0;
```

But if there are no messages at all `CountQuery` raises `IndexError` because rows were not returned:

```
Traceback (most recent call last):
  File "<ipython-input-12-07dd4b06f121>", line 1, in <module>
    await Conversation.annotate(messages_count=Count("messages")).filter(messages_count__gt=0).exclude(messages__id="00000000-0000-0000-0000-000000000000").count()
  File "/Users/mirrorrim/Library/Caches/pypoetry/virtualenvs/server-wQAZuLdb-py3.8/lib/python3.8/site-packages/tortoise/queryset.py", line 911, in _execute
    count = list(dict(result[0]).values())[0] - self.offset
IndexError: list index out of range
```
