### ISSUE TITLE
Annotate by field of the related model

### ISSUE THREAD

**Issue by mirrorrim** [tortoise/tortoise-orm#477]
Sometimes I need to annotate queryset with field of the related model.  

For example I want to get comments with an annotated user name for these models.

```python
from tortoise import fields
from tortoise.models import Model


class User(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=100, null=True, default=None)
    comments: fields.ReverseRelation["Comment"]


class Comment(Model):
    id = fields.IntField(pk=True)
    user: fields.ForeignKeyRelation["User"] = fields.ForeignKeyField(
        "models. User", on_delete=fields.CASCADE, related_name="comments"
    )
    text = fields.TextField()
```

In Django I can do something like this:

```python
comments = Comment.object.annotate(user_name=F("user__name"))
```

It would be nice to have similar functionality in Tortoise ORM:

```python
comments = await Comment.annotate(user_name=F("user__name"))
```

Thanks.

**Comment by lqmanh** [comment]
Not professional here but isn't it already supported by Tortoise ORM?
Have you had a look at [this](https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html?highlight=annotate#functions)?

**Comment by mirrorrim** [comment]
@lqmanh thanks for the asnwer! Indeed, this will work if you use an additional function, such as Coalesce (which is OK for my case), but sometimes I don't need any modifications, only join with additional field.

**Comment by lqmanh** [comment]
@mirrorrim Then you can just use `F` expression like that?

**Comment by mirrorrim** [comment]
@lqmanh unfortunately it doesn't work. It raises an exception like this:

```python
 In[3] i = await IncomePayment.annotate(
  ...:     description=F("invoice__description"),
  ...: )
Traceback (most recent call last):
  File "/Users/mirrorrim/Library/Caches/pypoetry/virtualenvs/server-wQAZuLdb-py3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3341, in run_code
    await eval(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-717be70f04d7>", line 1, in <module>
    i = await IncomePayment.annotate(
  File "/Users/mirrorrim/Library/Caches/pypoetry/virtualenvs/server-wQAZuLdb-py3.8/lib/python3.8/site-packages/tortoise/models.py", line 1049, in annotate
    return QuerySet(cls).annotate(**kwargs)
  File "/Users/mirrorrim/Library/Caches/pypoetry/virtualenvs/server-wQAZuLdb-py3.8/lib/python3.8/site-packages/tortoise/queryset.py", line 439, in annotate
    raise TypeError("value is expected to be Function instance")
TypeError: value is expected to be Function instance
```
