### ISSUE TITLE
FastApi Integration returns tortoise.exceptions.ConfigurationError

### ISSUE THREAD

**Issue by qzhang1** [tortoise/tortoise-orm#492]
**Describe the bug**
I'm trying to use tortoise-orm with FastApi. I have a fairly simple setup shown below. When I run uvicorn app.main:app --reload command, I get the following Error: 

```
ERROR:    Traceback (most recent call last):
  File "/home/qzhang/pyprojects/fastapi-tdd-docker/env/lib/python3.8/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/home/qzhang/pyprojects/fastapi-tdd-docker/env/lib/python3.8/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/home/qzhang/pyprojects/fastapi-tdd-docker/env/lib/python3.8/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "/home/qzhang/pyprojects/fastapi-tdd-docker/env/lib/python3.8/site-packages/tortoise/contrib/fastapi/__init__.py", line 92, in init_orm
    await Tortoise.init(config=config, config_file=config_file, db_url=db_url, modules=modules)
  File "/home/qzhang/pyprojects/fastapi-tdd-docker/env/lib/python3.8/site-packages/tortoise/__init__.py", line 527, in init
    raise ConfigurationError(
tortoise.exceptions.ConfigurationError: You should init either from "config", "config_file" or "db_url"
```

app/models/tortoise.py
```
from tortoise import fields, models
from tortoise.contrib.pydantic import pydantic_model_creator

class TextSummary(models.Model):
    url = fields.CharField(max_length=300)
    summary = fields.TextField()
    created_at = fields.DatetimeField(auto_now_add=True)

    def __str__(self):
        return self.url
```

app/main.py
```
import os
from fastapi import FastAPI, Depends, HTTPException
from pydantic import BaseModel

from tortoise.contrib.fastapi import register_tortoise
from app.config import get_settings, Settings

app = FastAPI(title="TDD/Docker FastApi Sampler")


@app.get('/ping')
async def pong(settings: Settings = Depends(get_settings)):
    return {
        'ping': 'pong!',
        "environment": settings.environment,
        "testing": settings.testing
    }


register_tortoise(app,
                  db_url=os.getenv("DATABASE_URL"),
                  modules={"models": ["app.models.tortoise"]},
                  generate_schemas=True,
                  add_exception_handlers=True)
```

**To Reproduce**
Host: Microsoft Windows 10 Home, Version 10.0.19041 Build 19041
WSL: Ubuntu-20.04
IDE: Visual Studio Code, Version 1.48.0

**Requirements.txt**
aiosqlite==0.15.0
asyncpg==0.21.0
click==7.1.2
fastapi==0.61.1
h11==0.9.0
httptools==0.1.1
iso8601==0.1.12
pydantic==1.6.1
PyPika==0.38.0
starlette==0.13.6
tortoise-orm==0.16.14
typing-extensions==3.7.4.3
uvicorn==0.11.5
uvloop==0.14.0
websockets==8.1

**Comment by long2ice** [comment]
Can you print value of `os.getenv("DATABASE_URL")`?

**Comment by averdones** [comment]
If you try what @long2ice said and you get `None`, then you don't have your environment variable DATABASE_URL set.

You could try:

`os.getenv("DATABASE_URL") = THE_URL_TO_YOUR_DATABASE`

before `register_tortoise`.
