### ISSUE TITLE
cannot connect from inside container - closed connection?

### ISSUE THREAD

**Issue by kpvf** [tortoise/tortoise-orm#556]
Hi thanks for the great software but unfortunately for me i have an issue and cannot figure out whats going on.
I have two containers one db one app. 
App connects to the container and runs fine can ping container etc, but when i start tortoise it crashes giving me this.

```
web_1     | Waiting for postgres...
web_1     | PostgreSQL started
web_1     | /usr/src/app/entrypoint.sh: 5: /usr/src/app/entrypoint.sh: !nc: not found
web_1     | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
web_1     | INFO:     Started reloader process [1] using statreload
web_1     | INFO:     Started server process [7]
web_1     | INFO:     Waiting for application startup.
web_1     | INFO:     starting up
web_1     | INFO:     Tortoise-ORM startup
web_1     |     connections: {'default': {'engine': 'tortoise.backends.asyncpg', 'credentials': {'port': 5432, 'database': 'web_dev', 'host': 'web-db', 'user': 'postgres', 'password': 'postgres'}}}
web_1     |     apps: {'models': {'models': ['app.models.tortoise'], 'default_connection': 'default'}}
web_1     | ERROR:    Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 517, in lifespan
web_1     |     await self.startup()
web_1     |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 494, in startup
web_1     |     await handler()
web_1     |   File "/usr/local/lib/python3.8/site-packages/tortoise/contrib/fastapi/__init__.py", line 92, in init_orm
web_1     |     await Tortoise.init(config=config, config_file=config_file, db_url=db_url, modules=modules)
web_1     |   File "/usr/local/lib/python3.8/site-packages/tortoise/__init__.py", line 555, in init
web_1     |     await cls._init_connections(connections_config, _create_db)
web_1     |   File "/usr/local/lib/python3.8/site-packages/tortoise/__init__.py", line 385, in _init_connections
web_1     |     await connection.create_connection(with_db=True)
web_1     |   File "/usr/local/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 94, in create_connection
web_1     |     self._pool = await asyncpg.create_pool(None, password=self.password, **self._template)
web_1     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/pool.py", line 398, in _async__init__
web_1     |     await self._initialize()
web_1     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/pool.py", line 426, in _initialize
web_1     |     await first_ch.connect()
web_1     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/pool.py", line 125, in connect
web_1     |     self._con = await self._pool._get_new_connection()
web_1     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/pool.py", line 468, in _get_new_connection
web_1     |     con = await connection.connect(
web_1     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1668, in connect
web_1     |     return await connect_utils._connect(
web_1     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 663, in _connect
web_1     |     raise last_error
web_1     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 652, in _connect
web_1     |     con = await _connect_addr(
web_1     |   File "/usr/local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 621, in _connect_addr
web_1     |     tr, pr = await asyncio.wait_for(
web_1     |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
web_1     |     return fut.result()
web_1     |   File "uvloop/loop.pyx", line 1974, in create_connection
web_1     |   File "uvloop/loop.pyx", line 1951, in uvloop.loop.Loop.create_connection
web_1     | OSError: [Errno 113] No route to host

```
When i comment out tortoise and run from cli schema creation i got this:
```
Traceback (most recent call last):
  File "app/db.py", line 33, in <module>
    run_async(generate_schemas())
  File "/usr/local/lib/python3.8/site-packages/tortoise/__init__.py", line 636, in run_async
    loop.run_until_complete(coro)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "app/db.py", line 23, in generate_schemas
    await Tortoise.init(
  File "/usr/local/lib/python3.8/site-packages/tortoise/__init__.py", line 555, in init
    await cls._init_connections(connections_config, _create_db)
  File "/usr/local/lib/python3.8/site-packages/tortoise/__init__.py", line 385, in _init_connections
    await connection.create_connection(with_db=True)
  File "/usr/local/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 94, in create_connection
    self._pool = await asyncpg.create_pool(None, password=self.password, **self._template)
  File "/usr/local/lib/python3.8/site-packages/asyncpg/pool.py", line 398, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.8/site-packages/asyncpg/pool.py", line 426, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.8/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.8/site-packages/asyncpg/pool.py", line 468, in _get_new_connection
    con = await connection.connect(
  File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1668, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 663, in _connect
    raise last_error
  File "/usr/local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 652, in _connect
    con = await _connect_addr(
  File "/usr/local/lib/python3.8/site-packages/asyncpg/connect_utils.py", line 621, in _connect_addr
    tr, pr = await asyncio.wait_for(
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('172.26.0.2', 5432)
```

link to db:
`postgres://postgres:postgres@web-db:5432/web_dev`

**Comment by kpvf** [comment]
Hi this can be closed now i have found issue. Problem is with firewall and iptables which are not setup by default as i use fedora and they use nftables where docker does some changes to firewall rules in iptables.
for future ref this might help someone.
https://superuser.com/questions/1581738/docker-containers-cannot-connect-to-internet-in-fedora-32

**Comment by long2ice** [comment]
OK
