### ISSUE TITLE
Version 0.14.18 installed with accel extras doesn't support Python 3.8

### ISSUE THREAD

**Issue by jstlaurent** [tortoise/tortoise-orm#562]
**Describe the bug**
When installing Tortoise ORM 0.14.18, changes made to the `uvloop` dependency requirements means that its version 0.12.2 gets installed, instead of 0.14.0 as was the case with Tortoise 0.16.17. `uvloop` added support for Python 3.8 in its version [0.14.0](https://github.com/MagicStack/uvloop/releases/tag/v0.14.0). 

When Tortoise gets initialized, the following error is raised:
```python
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/julien/Library/Caches/pypoetry/virtualenvs/platform-api-CTZslBuz-py3.8/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/Users/julien/Library/Caches/pypoetry/virtualenvs/platform-api-CTZslBuz-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 417, in run
    self.config.setup_event_loop()
  File "/Users/julien/Library/Caches/pypoetry/virtualenvs/platform-api-CTZslBuz-py3.8/lib/python3.8/site-packages/uvicorn/config.py", line 363, in setup_event_loop
    loop_setup()
  File "/Users/julien/Library/Caches/pypoetry/virtualenvs/platform-api-CTZslBuz-py3.8/lib/python3.8/site-packages/uvicorn/loops/auto.py", line 3, in auto_loop_setup
    import uvloop  # noqa
  File "/Users/julien/Library/Caches/pypoetry/virtualenvs/platform-api-CTZslBuz-py3.8/lib/python3.8/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
  File "uvloop/includes/stdlib.pxi", line 114, in init uvloop.loop
AttributeError: module 'sys' has no attribute 'set_coroutine_wrapper'
```

**To Reproduce**
- Create a project using Poetry as a dependency manager, using Python 3.8
- Set your project dependencies in `pyproject.toml` to this:
```toml
[tool.poetry.dependencies]
python = "^3.8"
fastapi = {version = "^0.61.2"}
tortoise-orm = {extras = ["accel"], version = "^0.16.18"}
uvicorn = "^0.12.2"
```
- Run `poetry update`
- Create a minimal FastAPI server in a file named `main.py`:
```python
from fastapi import FastAPI
from tortoise.contrib.fastapi import register_tortoise

app = FastAPI()
register_tortoise(
    app,
    db_url='',
    modules={
        'models': ['']
    }
)
```
- Run the server using uvicorn: `uvicorn main:app --reload`

**Expected behavior**
The FastApi server starts up normally.

**Additional context**
Might be worth adding some automated tests running on that configuration to prevent a regression in the future.

**Comment by long2ice** [comment]
I updated it in dev branch, just try it.

**Comment by jstlaurent** [comment]
It's fixed when using the latest from `develop`. Thanks!

**Comment by jstlaurent** [comment]
Would you mind keeping the issue open until the fix is released? I have my dependency pinned to 0.14.17 at the moment and I'd like to know when it's going to be ok to unpin it.

**Comment by long2ice** [comment]
Never mind, and you can also add git url as dependency.

**Comment by ALexALed** [comment]
Thank you for fixing this.
May I ask about the new release?
