### ISSUE TITLE
Saving models cloned from ones fetched from DB leads to `AttributeError` exception

### ISSUE THREAD

**Issue by droserasprout** [tortoise/tortoise-orm#633]
**Describe the bug**
`_custom_generated_pk` attribute not set in `Model._init_from_db` method. 

**To Reproduce**
```python
import asyncio
from tortoise import Tortoise, Model, fields, run_async


class SomeModel(Model):
    id = fields.IntField(pk=True)
    test = fields.TextField()


async def run():
    await Tortoise.init(db_url="sqlite://:memory:", modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()

    new_model = SomeModel(test='test')
    await new_model.save()

    existing_model = await SomeModel.filter(test='test').first()

    existing_model_clone = existing_model.clone()
    existing_model_clone.test = 'test_test'
    await existing_model_clone.save()

run_async(run())
```

```python
Traceback (most recent call last):
  File "/mnt/main/git/tortoise/models.py", line 23, in <module>
    run_async(run())
  File "/mnt/main/git/tortoise/.venv/lib/python3.9/site-packages/tortoise/__init__.py", line 681, in run_async
    loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/mnt/main/git/tortoise/models.py", line 21, in run
    await existing_model_clone.save()
  File "/mnt/main/git/tortoise/.venv/lib/python3.9/site-packages/tortoise/models.py", line 923, in save
    await executor.execute_insert(self)
  File "/mnt/main/git/tortoise/.venv/lib/python3.9/site-packages/tortoise/backends/base/executor.py", line 197, in execute_insert
    if not instance._custom_generated_pk:
AttributeError: 'SomeModel' object has no attribute '_custom_generated_pk'
```

**Expected behavior**
Cloned model successfully saved to the database.

**Additional context**
Python 3.9.1
tortoise-orm 0.16.20

**Comment by long2ice** [comment]
try use `existing_model.pk = None` then `await existing_model.save()`

**Comment by vicctorb2** [comment]
Have the same problem

**Comment by NightMarcher** [comment]
Same, `existing_model.pk = None` doesn`t work.

**Comment by long2ice** [comment]
The temporary method is `existing_model._custom_generated_pk = False` or `True`, depends your pk field setting
