### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'total_changes'

### ISSUE THREAD

**Issue by ns-phennessy** [tortoise/tortoise-orm#706]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/tf2maps/bot_zeus/cogs/tags.py", line 27, in on_message
    tag = await Tag.filter(key=key)
  File "/usr/local/lib/python3.7/dist-packages/tortoise/queryset.py", line 842, in _execute
    ).execute_select(self.query, custom_fields=list(self._annotations.keys()))
  File "/usr/local/lib/python3.7/dist-packages/tortoise/backends/base/executor.py", line 124, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/usr/local/lib/python3.7/dist-packages/tortoise/backends/sqlite/client.py", line 29, in translate_exceptions_
    return await func(self, query, *args)
  File "/usr/local/lib/python3.7/dist-packages/tortoise/backends/sqlite/client.py", line 133, in execute_query
    start = connection.total_changes
AttributeError: 'NoneType' object has no attribute 'total_changes'
```

**Summary**
I believe that there is an issue with the `Tortoise.init` finding and creating the database connection

There is code calling the init function from main.py, and the model in question is used later in a plugin under `cogs/tags.py`

**Folder structure:**
```
├── main.py
├── tags.sqlite
├── cogs/
│   ├── __init__.py
│   ├── tags.py
├── models/
│   ├── __init__.py
│   └── Tag.py
```

**models/Tag.py**
```python
from tortoise import Tortoise, fields
from tortoise.models import Model

class Tag(Model):
    id = fields.IntField(pk=True)
    key = fields.TextField()
    value = fields.CharField(max_length=1024)
    author = fields.CharField(max_length=128)
    date = fields.DatetimeField(null=True)
```

**Main.py**
```python

await Tortoise.init(
    db_url="sqlite://tags.sqlite",
    modules={'models': ["models.Tag"]}
)
```

**cogs/tags.py**
```python
async def on_message(self, message):
    key = message.content.lower()
    tag = await Tag.filter(key=key)
    await message.channel.send(tag.value)
```

**Comment by ns-phennessy** [comment]
Okay this appears to be caused by me using the `run_async` function inappropriately. Basically the bot is running its own asyncio loop and that caused the init function to run on another loop.

I'm a bit confused why that would cause an issue like this though?
