### ISSUE TITLE
`KeyError` on saving changed ForeignKeyField with `update_fields`

### ISSUE THREAD

**Issue by Olegt0rr** [tortoise/tortoise-orm#726]
**Describe the bug**
On trying to save changed foreign field with `update_fields` got an error.
```python
Traceback (most recent call last):
  File "draft.py", line 43, in run
    await event.save(update_fields=["tournament"])
  File "venv/lib/python3.8/site-packages/tortoise/models.py", line 930, in save
    await executor.execute_update(self, update_fields)
  File "venv/lib/python3.8/site-packages/tortoise/backends/base/executor.py", line 298, in execute_update
    value = self.column_map[field](instance_field, instance)
KeyError: 'tournament'
```

**To Reproduce**
```python
from tortoise import Tortoise, run_async
from tortoise.fields import (
    ForeignKeyField,
    ForeignKeyNullableRelation,
    IntField,
    ReverseRelation,
)
from tortoise.models import Model


class Tournament(Model):
    id = IntField(pk=True)
    events: ReverseRelation["Event"]


class Event(Model):
    id = IntField(pk=True)
    tournament: ForeignKeyNullableRelation[Tournament] = ForeignKeyField(
        "models.Tournament", related_name="events", null=True,
    )


async def run():
    await Tortoise.init(
        db_url="sqlite://:memory:",
        modules={"models": ["__main__"]},
    )
    await Tortoise.generate_schemas()

    # create objects
    tournament = await Tournament.create()
    event = await Event.create()

    # set tournament
    event.tournament = tournament

    # on `update_fields` we'll get an error: `KeyError: 'tournament'`
    await event.save(update_fields=["tournament"])

    # but without `update_fields` it works :)
    await event.save()


if __name__ == "__main__":
    run_async(run())
```

**Expected behavior**
Just save the field :)

**Comment by isaquealves** [comment]
Can confirm that!
Hope the following screencaps can serve as evidence.

|<img width="640" alt="Screen Shot 2021-04-21 at 2 50 33 PM" src="https://user-images.githubusercontent.com/204715/115598625-fc8d6200-a2b0-11eb-86f2-814062ef5541.png">|
|:--:| 
| *tortoise.backends.base.executor.BaseExecutor.execute_update* method tries to call column_map[field] where field is an item from update_fields, in this case 'tournament' |

|<img width="375" alt="Screen Shot 2021-04-21 at 2 53 34 PM" src="https://user-images.githubusercontent.com/204715/115598989-686fca80-a2b1-11eb-99d4-ac520409b10a.png">|
|:--:| 
| *column_map doesn't have the field name 'tournament' as a key.  Instead we found 'tournament_id'* |

### Workaround

When passing FK through 'update_fields' they should be suffixed with '_id'.

Obs.: The example is not fully functional. Tournament.create() is returning an object with id=0. To get the example working I had to add a new attribute to  Tournament model as follows:

```python
from tortoise import Tortoise, run_async
from tortoise.fields import (
    ForeignKeyField,
    ForeignKeyNullableRelation,
    IntField,
    ReverseRelation,
)
from tortoise.fields.data import CharField
from tortoise.models import Model

class Tournament(Model):
    id = IntField(pk=True)
    name = CharField(max_length=15)  # without this one, Tournament.create returns an object `tournament#id=0`
    events: ReverseRelation["Event"]


class Event(Model):
    id = IntField(pk=True)
    tournament: ForeignKeyNullableRelation[Tournament] = ForeignKeyField(
        "models.Tournament", related_name="events", null=True,
    )


async def run():
    await Tortoise.init(
        db_url="sqlite://:memory:",
        modules={"models": ["__main__"]},
    )
    await Tortoise.generate_schemas()

    # create objects
    tournament = await Tournament.create(name="Mortal Kombat")
    event = await Event.create()
    # set tournament
    event.tournament = tournament

    # on `update_fields` we should refer the db field name, i.e. 'tournament_id'
    await event.save(update_fields=["tournament_id"])

    # but without `update_fields` it works :)
    await event.save()


if __name__ == "__main__":
    run_async(run())
```

**Comment by Olegt0rr** [comment]
> # without this one, Tournament.create returns an object `tournament#id=0`
@isaquealves, seems it's another one bug :)

**Comment by Olegt0rr** [comment]
@long2ice why closed? Any solution?

**Comment by long2ice** [comment]
Just use id

**Comment by Olegt0rr** [comment]
This is a weird and illogical solution. 
Thus, I am forced to migrate all my projects to another db tool.

**Comment by long2ice** [comment]
Do what you want
