### ISSUE TITLE
 发现关于 `.select_related` 与 `.sql()` 的BUG

### ISSUE THREAD

**Issue by OpenHill** [tortoise/tortoise-orm#796]
# 发现关于 `.select_related` 与 `.sql()` 的BUG

### 版本 0.17.0

在正常情况下使用 `.sql()` 不会出现任何问题如：

```python
queryset = model1.all()
queryset.sql()
await queryset
# 这样不会发生错误
```

一旦`.select_related` 与 `.sql()`一起使用就会出现问题

```python
queryset = model1.all().select_related(model2_filed)
queryset.sql()
await queryset
# 这样就会出现问题
# tortoise.exceptions.OperationalError: (1054, "Unknown column 'model1__model2.filed' in 'field list'")
```

# 错误详情

```
Traceback (most recent call last):
  File "D:\lwj\wg\WeiGroup\sanic_rest_framework\views.py", line 118, in dispatch
    response = await response
  File "D:\lwj\wg\WeiGroup\sanic_rest_framework\mixins.py", line 73, in get
    return await self.retrieve(request, *args, **kwargs)
  File "D:\lwj\wg\WeiGroup\sanic_rest_framework\mixins.py", line 76, in retrieve
    instance = await self.get_object()
  File "D:\lwj\wg\WeiGroup\sanic_rest_framework\views.py", line 257, in get_object
    queryset = await self.filter_queryset(await self.get_queryset())
  File "D:\lwj\wg\WeiGroup\apps\mixing_station\views.py", line 100, in get_queryset
    a=await a
  File "D:\lwj\SaincTestForSRF\venv\lib\site-packages\tortoise\queryset.py", line 842, in _execute
    ).execute_select(self.query, custom_fields=list(self._annotations.keys()))
  File "D:\lwj\SaincTestForSRF\venv\lib\site-packages\tortoise\backends\base\executor.py", line 124, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "D:\lwj\SaincTestForSRF\venv\lib\site-packages\tortoise\backends\mysql\client.py", line 52, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: (1054, "Unknown column 'productinfomodel__concrete_station.note' in 'field list'")
```

**Comment by long2ice** [comment]
多次调用`.sql()`只有第一次正确，后续的关联关系会失效，是一个bug

**Comment by long2ice** [comment]
已修复
