### ISSUE TITLE
Execute custom SQL on PgSQL Database

### ISSUE THREAD

**Issue by Iamsdt** [tortoise/tortoise-orm#818]
**Describe the bug**

I am using Tortoise ORM with Fast API and PostgreSQL as database. And trying to access the PostgreSQL view, but always getting the below error

```
tortoise.exceptions.OperationalError: operator does not exist: & integer
```
**Complete stacktrace**
```
Traceback (most recent call last):
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./app/router/home/home.py", line 46, in get_more_data
    data2 = await trans.execute_query(f"""
  File "/home/shudipto/miniconda3/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 38, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: operator does not exist: & integer
HINT:  No operator matches the given name and argument type. You might need to add an explicit type cast.
```

**To Reproduce**
I used this example
https://github.com/tortoise/tortoise-orm/issues/191#issuecomment-532295132

My code:
```
async with in_transaction() as trans:
       data2 = await trans.execute_query(f"""
            SELECT * FROM public.episode_card where title = &1""", ["abc"])
```

**Expected behavior**
it should be executed successfully

**Additional context**

**Comment by lsabi** [comment]
I believe your query is using the wrong indicator for the value. It should be $ not &. At least, so is shown in the official docs of asyncpg [https://magicstack.github.io/asyncpg/current/usage.html](https://magicstack.github.io/asyncpg/current/usage.html)

Your code should be
```
async with in_transaction() as trans:
       data2 = await trans.execute_query(f"""
            SELECT * FROM public.episode_card where title = $1""", ["abc"])
```

**Comment by Iamsdt** [comment]
Thanks, @lsabi,
I guess it was typo mistake on this answer (https://github.com/tortoise/tortoise-orm/issues/191#issuecomment-532295132)
