### ISSUE TITLE
how to run tortoise orm in python shell like django manage.py shell

### ISSUE THREAD

**Issue by sakthiRathinam** [tortoise/tortoise-orm#840]
>>> from shell import *
>>> run_async(main())
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tortoise/models.py", line 265, in db
    return current_transaction_map[self.default_connection].get()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tortoise/__init__.py", line 679, in run_async
    loop.run_until_complete(coro)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/shell.py", line 30, in main
    # await dps()
  File "/app/shell.py", line 22, in dps
    #     await Tournament.create(name='Another Tournament')
  File "/usr/local/lib/python3.9/site-packages/tortoise/models.py", line 1031, in create
    db = kwargs.get("using_db") or cls._meta.db
  File "/usr/local/lib/python3.9/site-packages/tortoise/models.py", line 267, in db
    raise ConfigurationError("No DB associated to model")
tortoise.exceptions.ConfigurationError: No DB associated to model
>>> init()
<coroutine object init at 0x7fec6672e5c0>
>>> User.all()
<stdin>:1: RuntimeWarning: coroutine 'init' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
<tortoise.queryset.QuerySet object at 0x7fec674d0a90>
>>> User.all()[0].username
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'QuerySet' object is not subscriptable
>>> u=User.first()
>>> u.username
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'QuerySet' object has no attribute 'username'
>>> u
<tortoise.queryset.QuerySet object at 0x7fec66e899a0>
>>> u=User.all()
>>> for user in u:
...     print(user.username)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'QuerySet' object is not iterable
>>> u.count()
<tortoise.queryset.CountQuery object at 0x7fec6672e5c0>
>>> u
<tortoise.queryset.QuerySet object at 0x7fec674d0a90>
>>> async for user in u:
...     print(user.username)
... 
  File "<stdin>", line 1
SyntaxError: 'async for' outside async function
>>> async def print():
...     async for user in u:
... ...     print(user.username)
  File "<stdin>", line 3
    ...     print(user.username)
IndentationError: expected an indented block
>>> async def print():
...     async for user in u:
...             print(user.username)
... 
>>> print()
<coroutine object print at 0x7fec66ef04c0>
>>> s=print()
>>> s
<stdin>:1: RuntimeWarning: coroutine 'print' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
<coroutine object print at 0x7fec6674eb40>
>>> s = await print()
  File "<stdin>", line 1
SyntaxError: 'await' outside function
>>> user = await User.first()
  File "<stdin>", line 1

**Comment by long2ice** [comment]
see https://github.com/tortoise/tortoise-cli

**Comment by sakthiRathinam** [comment]
ERROR: Could not find a version that satisfies the requirement tortoise-cli (from versions: none)
ERROR: No matching distribution found for tortoise-cli
there is no matching distribution for tortoise-cli can you please check your pypi

**Comment by long2ice** [comment]
Try that again, which not release before
