### ISSUE TITLE
How to use the fields of the custom function in annotate in the filter

### ISSUE THREAD

**Issue by jakehu** [tortoise/tortoise-orm#843]
Function
```python
from tortoise.expressions import F
from pypika.terms import Function

class JsonContains(Function):
    def __init__(self, field: F,  value: any):
        super().__init__("JSON_CONTAINS", field, value, '$')
```

Model
```python
from tortoise import Model, fields

class ag_certificate(Model):
    id = fields.IntField(pk=True)
    domain = fields.JSONField()

    def __str__(self):
        return str(self.id)
```

USE
```python
await self.model.all().annotate(is_ex=JsonContains(F('ip'), row['ip'])).filter(
                is_ex__gt=1).limit(limit).offset(offset).values()
```

ERROR
```python
Traceback (most recent call last):
  File "/Users/jakehu/.pyenv/versions/auth-getway/lib/python3.9/site-packages/sanic/app.py", line 770, in handle_request
    response = await response
  File "/Users/jakehu/Documents/zbj/auth-getway-api/app/controllers/application/ipgroup.py", line 30, in list
    res = await service.list(request,row)
  File "/Users/jakehu/Documents/zbj/auth-getway-api/app/services/application/ipgroup.py", line 27, in list
    print(self.model.all().annotate(is_ex=JsonContains('ip', row['ip'])).filter(
  File "/Users/jakehu/.pyenv/versions/auth-getway/lib/python3.9/site-packages/tortoise/queryset.py", line 248, in sql
    return self.as_query().get_sql(**kwargs)
  File "/Users/jakehu/.pyenv/versions/auth-getway/lib/python3.9/site-packages/tortoise/queryset.py", line 254, in as_query
    self._make_query()
  File "/Users/jakehu/.pyenv/versions/auth-getway/lib/python3.9/site-packages/tortoise/queryset.py", line 1366, in _make_query
    self.resolve_filters(
  File "/Users/jakehu/.pyenv/versions/auth-getway/lib/python3.9/site-packages/tortoise/queryset.py", line 129, in resolve_filters
    modifier &= node.resolve(model, annotations, custom_filters, model._meta.basetable)
  File "/Users/jakehu/.pyenv/versions/auth-getway/lib/python3.9/site-packages/tortoise/query_utils.py", line 390, in resolve
    return self._resolve_kwargs(model, table)
  File "/Users/jakehu/.pyenv/versions/auth-getway/lib/python3.9/site-packages/tortoise/query_utils.py", line 346, in _resolve_kwargs
    filter_modifier = self._resolve_custom_kwarg(model, key, value, table)
  File "/Users/jakehu/.pyenv/versions/auth-getway/lib/python3.9/site-packages/tortoise/query_utils.py", line 287, in _resolve_custom_kwarg
    annotation_info = annotation.resolve(model, table)
AttributeError: 'JsonContains' object has no attribute 'resolve'
```

**Comment by long2ice** [comment]
The `Function` should import from `tortoise.functions`

**Comment by jakehu** [comment]
You are right
