### ISSUE TITLE
`initializer()` not working

### ISSUE THREAD

**Issue by MrAngry** [tortoise/tortoise-orm#910]
When trying to use initializer I run into error:
Usage:

```
        initializer(['app.model.orm'],app_label='base')

```
```
Error
Traceback (most recent call last):
  File "F:\LibTools\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\asynctest\case.py", line 293, in run
    self._setUp()
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\asynctest\case.py", line 248, in _setUp
    self.loop.run_until_complete(self.setUp())
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\asynctest\case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "F:\LibTools\Python38\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "F:\LibTools\Python38\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "A:\TDS\fastapi-elastic\tests\projects\cmt\test_cmt_campaign_parameters.py", line 38, in setUp
    initializer(['app.model.orm'], app_label='base')
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\tortoise\contrib\test\__init__.py", line 117, in initializer
    loop.run_until_complete(_init_db(_CONFIG))
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\asynctest\case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "F:\LibTools\Python38\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "F:\LibTools\Python38\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\tortoise\contrib\test\__init__.py", line 70, in _init_db
    await Tortoise.init(config)
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\tortoise\__init__.py", line 599, in init
    cls._init_apps(apps_config)
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\tortoise\__init__.py", line 439, in _init_apps
    cls._init_relations()
  File "A:\TDS\fastapi-elastic\venv-work\lib\site-packages\tortoise\__init__.py", line 148, in _init_relations
    if model._meta._inited:
AttributeError: 'dict' object has no attribute '_meta'

```

After inspection I saw that initiazlier wrongly adds `__bultins__` to models in apps list:

```
apps: {
      "base": {
       "MyModel_1": ....
       ....
       "__builtins__": ....
       }
````

**Comment by MrAngry** [comment]
After some more debugging the issue appears if somewhere in code before `initializer()` a call to `init_models()` is made
